/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/agent-environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List V1 Agent Environments */
        get: operations["list_v1_agent_environments_v1_agent_environments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List V2 Deployments */
        get: operations["list_v2_deployments_v2_deployments_get"];
        put?: never;
        /** Create V2 Deployment */
        post: operations["create_v2_deployment_v2_deployments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deployments/by-request/{deploy_request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get V2 Deploy Request Status */
        get: operations["get_v2_deploy_request_status_v2_deployments_by_request__deploy_request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deployments/{deployment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get V2 Deployment */
        get: operations["get_v2_deployment_v2_deployments__deployment_id__get"];
        put?: never;
        post?: never;
        /** Delete V2 Deployment */
        delete: operations["delete_v2_deployment_v2_deployments__deployment_id__delete"];
        options?: never;
        head?: never;
        /** Update V2 Deployment */
        patch: operations["update_v2_deployment_v2_deployments__deployment_id__patch"];
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/agents/{agent_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set V2 Agent Enabled */
        patch: operations["set_v2_agent_enabled_v2_deployments__deployment_id__agents__agent_type__patch"];
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/agents/{agent_type}/ai-provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rebind V2 Agent Ai Provider */
        patch: operations["rebind_v2_agent_ai_provider_v2_deployments__deployment_id__agents__agent_type__ai_provider_patch"];
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/terminal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create V2 Deployment Terminal Session */
        post: operations["create_v2_deployment_terminal_session_v2_deployments__deployment_id__terminal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/runtime-ui/redemption": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create V2 Deployment Runtime Ui Redemption */
        post: operations["create_v2_deployment_runtime_ui_redemption_v2_deployments__deployment_id__runtime_ui_redemption_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart V2 Deployment */
        post: operations["restart_v2_deployment_v2_deployments__deployment_id__restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start V2 Deployment */
        post: operations["start_v2_deployment_v2_deployments__deployment_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop V2 Deployment */
        post: operations["stop_v2_deployment_v2_deployments__deployment_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkout V2 Subscription */
        post: operations["checkout_v2_subscription_v2_subscription_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel V2 Subscription */
        post: operations["cancel_v2_subscription_v2_subscription_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/fix-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fix Payment V2 Subscription */
        post: operations["fix_payment_v2_subscription_v2_subscription_fix_payment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/billing-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List V2 Subscription Billing History */
        get: operations["list_v2_subscription_billing_history_v2_subscription_billing_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/plan/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change V2 Subscription Plan */
        post: operations["change_v2_subscription_plan_v2_subscription_plan_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/plan/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quote V2 Subscription Plan Change */
        post: operations["quote_v2_subscription_plan_change_v2_subscription_plan_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List V2 Subscription Plans */
        get: operations["list_v2_subscription_plans_v2_subscription_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Portal V2 Subscription */
        post: operations["portal_v2_subscription_v2_subscription_portal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quote V2 Subscription */
        post: operations["quote_v2_subscription_v2_subscription_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume V2 Subscription */
        post: operations["resume_v2_subscription_v2_subscription_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hosted V2 Usage Summary */
        get: operations["hosted_v2_usage_summary_v2_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wallet */
        get: operations["get_wallet_v2_wallet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/wallet/auto-reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Wallet Auto Reload */
        put: operations["update_wallet_auto_reload_v2_wallet_auto_reload_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/wallet/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List V2 Wallet Ledger */
        get: operations["list_v2_wallet_ledger_v2_wallet_ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/wallet/topup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Wallet Topup */
        post: operations["create_wallet_topup_v2_wallet_topup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * V1AgentEnvironmentsResponse
         * @description Cloud-api environment ids claimed by the user's live v1 deployments.
         */
        V1AgentEnvironmentsResponse: {
            /** Environment Ids */
            environment_ids: string[];
        };
        /** V1UserFeatureResolution */
        V1UserFeatureResolution: {
            /** Enabled */
            enabled: boolean;
            source: components["schemas"]["V1UserFeatureResolutionSource"];
        };
        /**
         * V1UserFeatureResolutionSource
         * @enum {string}
         */
        V1UserFeatureResolutionSource: "default" | "rule_user_id" | "rule_clerk_id" | "rule_email" | "rule_email_domain" | "rule_referral_l1";
        /** V1UserProductCapabilities */
        V1UserProductCapabilities: {
            /**
             * Can Use V1
             * @default true
             */
            can_use_v1: boolean;
            /**
             * Can Use V2
             * @default false
             */
            can_use_v2: boolean;
            /**
             * Can Use Plan C Billing
             * @default false
             */
            can_use_plan_c_billing: boolean;
        };
        /** V1UserResponse */
        V1UserResponse: {
            /**
             * Id
             * Format: sqid
             * @example usr_K8fJ3pQm
             */
            id: string;
            /** Clerk Id */
            clerk_id: string;
            /** Email */
            email: string | null;
            /** Name */
            name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Settings */
            settings: {
                [key: string]: components["schemas"]["V1UserFeatureResolution"];
            };
            /** Evm Wallet Address */
            evm_wallet_address?: string | null;
            capabilities: components["schemas"]["V1UserProductCapabilities"];
        };
        /** V2AiProviderBindingInfo */
        V2AiProviderBindingInfo: {
            /** Provider Id */
            provider_id?: string | null;
            /** Provider Ids */
            provider_ids?: string[];
            /**
             * Auth Kind
             * @enum {string}
             */
            auth_kind: "unmanaged" | "managed" | "api_key" | "codex_oauth";
            primary_model?: components["schemas"]["V2AiProviderPrimaryModelRef"] | null;
        };
        /** V2AiProviderPrimaryModelRef */
        V2AiProviderPrimaryModelRef: {
            /** Provider Id */
            provider_id: string;
            /** Model */
            model: string;
        };
        /** V2BillingOfferResponse */
        V2BillingOfferResponse: {
            /** Billing Term Months */
            billing_term_months: number;
            /** Price Cents */
            price_cents: number;
            /** Effective Monthly Price Cents */
            effective_monthly_price_cents: number;
            /** Discount Percent */
            discount_percent: number;
        };
        /** V2CheckoutResponse */
        V2CheckoutResponse: {
            /**
             * Flow Type
             * @default checkout_session
             * @enum {string}
             */
            flow_type: "checkout_session" | "subscription_activation";
            /**
             * Funding Source
             * @default stripe
             * @enum {string}
             */
            funding_source: "stripe" | "wallet";
            /** Action Url */
            action_url?: string | null;
            /**
             * Checkout Url
             * @default
             */
            checkout_url: string;
            /** Client Secret */
            client_secret?: string | null;
            /** Subscription Id */
            subscription_id?: number | null;
            /** Invoice Id */
            invoice_id?: string | null;
            /** Deployment Id */
            deployment_id?: string | null;
            /** Deploy Request Id */
            deploy_request_id?: string | null;
            /** Debited Credits */
            debited_credits?: string | null;
            /** Balance After Credits */
            balance_after_credits?: string | null;
            /** Current Period Start */
            current_period_start?: string | null;
            /** Current Period End */
            current_period_end?: string | null;
            /** Entitled Until */
            entitled_until?: string | null;
        };
        /** V2ComputeBillingHistoryItem */
        V2ComputeBillingHistoryItem: {
            /** Id */
            id: string;
            /**
             * Funding Source
             * @enum {string}
             */
            funding_source: "stripe" | "wallet";
            /** Compute Subscription Id */
            compute_subscription_id: number;
            /** Plan Slug */
            plan_slug: string;
            /** Status */
            status: string;
            /** Amount Cents */
            amount_cents: number;
            /**
             * Currency
             * @default usd
             */
            currency: string;
            /** Credits */
            credits?: string | null;
            /** Points Per Usd */
            points_per_usd?: number | null;
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end?: string | null;
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /** Stripe Invoice Id */
            stripe_invoice_id?: string | null;
            /** Stripe Invoice Number */
            stripe_invoice_number?: string | null;
            /** Hosted Invoice Url */
            hosted_invoice_url?: string | null;
        };
        /** V2ComputeBillingHistoryResponse */
        V2ComputeBillingHistoryResponse: {
            /** Data */
            data?: components["schemas"]["V2ComputeBillingHistoryItem"][];
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** V2ComputeCheckoutRequest */
        V2ComputeCheckoutRequest: {
            /**
             * Plan Slug
             * @enum {string}
             */
            plan_slug: "compute_basic" | "compute_performance";
            /**
             * Billing Term Months
             * @default 1
             * @enum {integer}
             */
            billing_term_months: 1 | 12;
            /**
             * Funding Source
             * @enum {string}
             */
            funding_source: "stripe" | "wallet";
            deploy_config?: components["schemas"]["V2HostedDeployRequest"] | null;
            /** Upgrade Deployment Id */
            upgrade_deployment_id?: string | null;
            /**
             * Ui Mode
             * @default custom
             */
            ui_mode: string;
            /** Locale */
            locale?: string | null;
            quote?: components["schemas"]["V2ComputeSubscriptionQuoteResponse-Input"] | null;
        };
        /** V2ComputeFixPaymentRequest */
        V2ComputeFixPaymentRequest: {
            /** Locale */
            locale?: string | null;
            /** Deployment Id */
            deployment_id?: string | null;
        };
        /** V2ComputePlanChangeQuoteRequest */
        V2ComputePlanChangeQuoteRequest: {
            /** Subscription Id */
            subscription_id: number;
            /**
             * Target Plan Slug
             * @enum {string}
             */
            target_plan_slug: "compute_basic" | "compute_performance";
            /**
             * Target Billing Term Months
             * @enum {integer}
             */
            target_billing_term_months: 1 | 12;
            /** Funding Source */
            funding_source?: ("stripe" | "wallet") | null;
        };
        /** V2ComputePlanChangeQuoteResponse */
        V2ComputePlanChangeQuoteResponse: {
            /** Operation Id */
            operation_id: string;
            /** Subscription Id */
            subscription_id: number;
            /** Funding Source */
            funding_source?: ("stripe" | "wallet") | null;
            /** Current Plan Slug */
            current_plan_slug: string;
            /** Target Plan Slug */
            target_plan_slug: string;
            /**
             * Current Billing Term Months
             * @enum {integer}
             */
            current_billing_term_months: 1 | 12;
            /**
             * Target Billing Term Months
             * @enum {integer}
             */
            target_billing_term_months: 1 | 12;
            /**
             * Change Kind
             * @enum {string}
             */
            change_kind: "immediate_upgrade" | "scheduled_downgrade";
            /**
             * Status
             * @default quoted
             * @constant
             */
            status: "quoted";
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /**
             * Proration Date
             * Format: date-time
             */
            proration_date: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Amount Cents */
            amount_cents: number;
            /** Amount Credits */
            amount_credits?: string | null;
            /** Points Per Usd */
            points_per_usd?: number | null;
            /**
             * Currency
             * @default usd
             */
            currency: string;
            /** Stripe Invoice Preview Id */
            stripe_invoice_preview_id?: string | null;
        };
        /** V2ComputePlanChangeRequest */
        V2ComputePlanChangeRequest: {
            /** Operation Id */
            operation_id: string;
        };
        /** V2ComputePlanChangeResponse */
        V2ComputePlanChangeResponse: {
            /** Operation Id */
            operation_id: string;
            /** Subscription Id */
            subscription_id: number;
            /** Funding Source */
            funding_source?: ("stripe" | "wallet") | null;
            /** Current Plan Slug */
            current_plan_slug: string;
            /** Target Plan Slug */
            target_plan_slug: string;
            /**
             * Target Billing Term Months
             * @enum {integer}
             */
            target_billing_term_months: 1 | 12;
            /**
             * Status
             * @enum {string}
             */
            status: "awaiting_payment" | "awaiting_projection" | "scheduled" | "complete";
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /** Funding Invoice Id */
            funding_invoice_id?: string | null;
        };
        /** V2ComputePortalRequest */
        V2ComputePortalRequest: {
            /** Locale */
            locale?: string | null;
        };
        /** V2ComputeSubscriptionActionResponse */
        V2ComputeSubscriptionActionResponse: {
            /** Status */
            status: string;
            /** Funding Source */
            funding_source?: ("stripe" | "wallet") | null;
            /** Billing Term Months */
            billing_term_months: number;
            /** Cancel At Period End */
            cancel_at_period_end: boolean;
            /** Current Period End */
            current_period_end?: string | null;
            /** Cancel At */
            cancel_at?: string | null;
            /** Invoice Due At */
            invoice_due_at?: string | null;
            /** Recovery Action */
            recovery_action?: ("top_up" | "fix_payment" | "start_new") | null;
            /** Message */
            message?: string | null;
        };
        /** V2ComputeSubscriptionCancelRequest */
        V2ComputeSubscriptionCancelRequest: {
            /**
             * Deployment Id
             * Format: sqid
             * @example hdep_K8fJ3pQm
             */
            deployment_id: string;
        };
        /** V2ComputeSubscriptionQuoteRequest */
        V2ComputeSubscriptionQuoteRequest: {
            /**
             * Plan Slug
             * @enum {string}
             */
            plan_slug: "compute_basic" | "compute_performance";
            /**
             * Billing Term Months
             * @default 1
             * @enum {integer}
             */
            billing_term_months: 1 | 12;
            /**
             * Funding Source
             * @enum {string}
             */
            funding_source: "stripe" | "wallet";
        };
        /** V2ComputeSubscriptionQuoteResponse */
        "V2ComputeSubscriptionQuoteResponse-Input": {
            /**
             * Plan Slug
             * @enum {string}
             */
            plan_slug: "compute_basic" | "compute_performance";
            /**
             * Billing Term Months
             * @enum {integer}
             */
            billing_term_months: 1 | 12;
            /**
             * Funding Source
             * @enum {string}
             */
            funding_source: "stripe" | "wallet";
            /**
             * Currency
             * @default usd
             */
            currency: string;
            /** Term Price Cents */
            term_price_cents: number;
            /** Preview Invoice Id */
            preview_invoice_id?: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Debit Credits */
            debit_credits?: number | string | null;
            /** Points Per Usd */
            points_per_usd?: number | null;
            /** Balance Before Credits */
            balance_before_credits?: number | string | null;
            /** Balance After Credits */
            balance_after_credits?: number | string | null;
        };
        /** V2ComputeSubscriptionQuoteResponse */
        "V2ComputeSubscriptionQuoteResponse-Output": {
            /**
             * Plan Slug
             * @enum {string}
             */
            plan_slug: "compute_basic" | "compute_performance";
            /**
             * Billing Term Months
             * @enum {integer}
             */
            billing_term_months: 1 | 12;
            /**
             * Funding Source
             * @enum {string}
             */
            funding_source: "stripe" | "wallet";
            /**
             * Currency
             * @default usd
             */
            currency: string;
            /** Term Price Cents */
            term_price_cents: number;
            /** Preview Invoice Id */
            preview_invoice_id?: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Debit Credits */
            debit_credits?: string | null;
            /** Points Per Usd */
            points_per_usd?: number | null;
            /** Balance Before Credits */
            balance_before_credits?: string | null;
            /** Balance After Credits */
            balance_after_credits?: string | null;
        };
        /** V2ComputeSubscriptionResumeRequest */
        V2ComputeSubscriptionResumeRequest: {
            /**
             * Deployment Id
             * Format: sqid
             * @example hdep_K8fJ3pQm
             */
            deployment_id: string;
        };
        /** V2DeploymentDeleteResponse */
        V2DeploymentDeleteResponse: {
            /** Status */
            status: string;
            /** Cvm Deleted */
            cvm_deleted: boolean;
            /**
             * Subscription Cancel Failed
             * @default false
             */
            subscription_cancel_failed: boolean;
            subscription?: components["schemas"]["V2DeploymentDeleteSubscriptionInfo"] | null;
        };
        /** V2DeploymentDeleteSubscriptionInfo */
        V2DeploymentDeleteSubscriptionInfo: {
            /** Cancel At Period End */
            cancel_at_period_end: boolean;
            /** Current Period End */
            current_period_end?: string | null;
        };
        /** V2DeploymentLifecycleResponse */
        V2DeploymentLifecycleResponse: {
            /** Status */
            status: string;
            /** Upgrade Task Id */
            upgrade_task_id?: string | null;
            /** Upgrade Status */
            upgrade_status?: string | null;
        };
        /** V2DeploymentRuntimeUiRedemptionResponse */
        V2DeploymentRuntimeUiRedemptionResponse: {
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** V2DeploymentTerminalSessionResponse */
        V2DeploymentTerminalSessionResponse: {
            /**
             * Deployment Id
             * Format: sqid
             * @example hdep_K8fJ3pQm
             */
            deployment_id: string;
            /** Websocket Url */
            websocket_url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** V2HostedComputeSubscriptionInfo */
        V2HostedComputeSubscriptionInfo: {
            /** Subscription Id */
            subscription_id?: number | null;
            /** Status */
            status: string;
            /** Funding Source */
            funding_source?: ("stripe" | "wallet") | null;
            /**
             * Payment State
             * @default ok
             * @enum {string}
             */
            payment_state: "ok" | "past_due" | "requires_action" | "unpaid";
            /** Billing Term Months */
            billing_term_months: number;
            /** Price Cents */
            price_cents?: number | null;
            /**
             * Currency
             * @default usd
             */
            currency: string;
            /**
             * Cancel At Period End
             * @default false
             */
            cancel_at_period_end: boolean;
            /** Current Period End */
            current_period_end?: string | null;
            /** Cancel At */
            cancel_at?: string | null;
            /** Canceled At */
            canceled_at?: string | null;
            /** Latest Failed Invoice Id */
            latest_failed_invoice_id?: string | null;
            /** Latest Failed Invoice Hosted Url */
            latest_failed_invoice_hosted_url?: string | null;
            /** Next Payment Attempt At */
            next_payment_attempt_at?: string | null;
            /** Recovery Action */
            recovery_action?: ("top_up" | "fix_payment" | "start_new") | null;
            /** Pending Plan Slug */
            pending_plan_slug?: string | null;
        };
        /** V2HostedConfigRequest */
        V2HostedConfigRequest: {
            /** Primary Model */
            primary_model?: string | components["schemas"]["V2AiProviderPrimaryModelRef"] | null;
            /** Channel */
            channel?: string | null;
            /** Telegram Bot Token */
            telegram_bot_token?: string | null;
            /** Telegram Allowed Usernames */
            telegram_allowed_usernames?: string[] | null;
            /** Discord Bot Token */
            discord_bot_token?: string | null;
            /** Discord Guild Id */
            discord_guild_id?: string | null;
            /** Slack Bot Token */
            slack_bot_token?: string | null;
            /** Slack App Token */
            slack_app_token?: string | null;
            /** Assistant Name */
            assistant_name?: string | null;
            /** Language */
            language?: ("en" | "es" | "fr" | "de" | "ja" | "ko" | "pt" | "zh-CN" | "zh-TW") | null;
            /** Timezone */
            timezone?: string | null;
            /** Public Ports */
            public_ports?: number[] | null;
            /** Runtime */
            runtime?: ("openclaw" | "hermes") | null;
        };
        /** V2HostedDeployRequest */
        V2HostedDeployRequest: {
            /**
             * Compute Plan Slug
             * @enum {string}
             */
            compute_plan_slug: "compute_basic" | "compute_performance";
            /** Primary Model */
            primary_model?: string | components["schemas"]["V2AiProviderPrimaryModelRef"] | null;
            /** Channel */
            channel?: string | null;
            /** Telegram Bot Token */
            telegram_bot_token?: string | null;
            /** Telegram Allowed Usernames */
            telegram_allowed_usernames?: string[] | null;
            /** Discord Bot Token */
            discord_bot_token?: string | null;
            /** Discord Guild Id */
            discord_guild_id?: string | null;
            /** Slack Bot Token */
            slack_bot_token?: string | null;
            /** Slack App Token */
            slack_app_token?: string | null;
            /** Model */
            model?: string | null;
            /** Assistant Name */
            assistant_name?: string | null;
            /** Language */
            language?: ("en" | "es" | "fr" | "de" | "ja" | "ko" | "pt" | "zh-CN" | "zh-TW") | null;
            /** Timezone */
            timezone?: string | null;
            /** Public Ports */
            public_ports?: number[] | null;
            /**
             * Runtime
             * @enum {string}
             */
            runtime: "openclaw" | "hermes";
            /** Deploy Request Id */
            deploy_request_id?: string | null;
            /** Ai Provider Id */
            ai_provider_id?: string | null;
            /** Provider Ids */
            provider_ids?: string[];
            /**
             * Ai Provider Auth Kind
             * @enum {string}
             */
            ai_provider_auth_kind: "unmanaged" | "managed" | "api_key" | "codex_oauth";
            /** Ai Provider Bootstrap */
            ai_provider_bootstrap?: {
                [key: string]: unknown;
            } | null;
            config?: components["schemas"]["V2HostedConfigRequest"] | null;
        };
        /** V2HostedDeployRequestStatusResponse */
        V2HostedDeployRequestStatusResponse: {
            /** Deploy Request Id */
            deploy_request_id: string;
            /**
             * Request Status
             * @enum {string}
             */
            request_status: "pending" | "ready" | "processing" | "succeeded" | "failed" | "expired" | "superseded";
            /** Deployment Id */
            deployment_id?: string | null;
            /** Deployment Status */
            deployment_status?: string | null;
        };
        /** V2HostedDeploymentDetailsInfo */
        V2HostedDeploymentDetailsInfo: {
            /**
             * Compute Plan Slug
             * @enum {string}
             */
            compute_plan_slug: "compute_basic" | "compute_performance";
            /**
             * Mux Enabled
             * @default false
             */
            mux_enabled: boolean;
            /**
             * Telegram Mux Enabled
             * @default false
             */
            telegram_mux_enabled: boolean;
            /**
             * Discord Mux Enabled
             * @default false
             */
            discord_mux_enabled: boolean;
            /**
             * Whatsapp Mux Enabled
             * @default false
             */
            whatsapp_mux_enabled: boolean;
            /**
             * Imessage Mux Enabled
             * @default false
             */
            imessage_mux_enabled: boolean;
            /**
             * Kobb Available
             * @default false
             */
            kobb_available: boolean;
            /** Primary Model */
            primary_model?: string | null;
            /** Ai Provider Id */
            ai_provider_id?: string | null;
            /**
             * Ai Provider Auth Kind
             * @enum {string}
             */
            ai_provider_auth_kind: "unmanaged" | "managed" | "api_key" | "codex_oauth";
            /** Ai Provider Bindings */
            ai_provider_bindings?: {
                [key: string]: components["schemas"]["V2AiProviderBindingInfo"];
            };
            /** Telegram Bot Username */
            telegram_bot_username?: string | null;
            /** Telegram Entry Url */
            telegram_entry_url?: string | null;
            /** Telegram Provider */
            telegram_provider?: string | null;
            /** Discord Guild Id */
            discord_guild_id?: string | null;
            /** Public Ports */
            public_ports?: number[];
            /**
             * Runtime
             * @enum {string}
             */
            runtime: "openclaw" | "hermes";
            /** Clawdi Cloud Environments */
            clawdi_cloud_environments?: {
                [key: string]: string;
            };
            /** Vcpu */
            vcpu?: number | null;
            /** Ram Gb */
            ram_gb?: number | null;
            /** Disk Gb */
            disk_gb?: number | null;
        };
        /** V2HostedDeploymentResponse */
        V2HostedDeploymentResponse: {
            /**
             * Id
             * Format: sqid
             * @example hdep_K8fJ3pQm
             */
            id: string;
            /**
             * User Id
             * Format: sqid
             * @example usr_K8fJ3pQm
             */
            user_id: string;
            /** Deploy Request Id */
            deploy_request_id?: string | null;
            /** Name */
            name: string;
            /** App Id */
            app_id: string;
            /** Backend */
            backend?: string | null;
            /**
             * Status
             * @default unknown
             */
            status: string;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Endpoints */
            endpoints?: string[];
            /** Native Url */
            native_url?: string | null;
            /** Openclaw Control Ui Url */
            openclaw_control_ui_url?: string | null;
            /** Hermes Control Ui Url */
            hermes_control_ui_url?: string | null;
            config_info?: components["schemas"]["V2HostedDeploymentDetailsInfo"] | null;
            compute_subscription?: components["schemas"]["V2HostedComputeSubscriptionInfo"] | null;
            last_funding_event?: components["schemas"]["V2HostedFundingEventInfo"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Upgrade Available
             * @default false
             */
            upgrade_available: boolean;
        };
        /** V2HostedFundingEventInfo */
        V2HostedFundingEventInfo: {
            /**
             * Type
             * @constant
             */
            type: "compute_subscription_fallback";
            /**
             * Funding Source
             * @enum {string}
             */
            funding_source: "stripe" | "wallet";
            /**
             * Reason
             * @enum {string}
             */
            reason: "payment_failure" | "canceled" | "refunded" | "disputed" | "admin_forced";
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Prior Plan Slug */
            prior_plan_slug: string;
            /** Subscription Id */
            subscription_id: number;
        };
        /** V2HostedUsageDay */
        V2HostedUsageDay: {
            /** Date */
            date: string;
            /** Credits */
            credits: number;
        };
        /** V2HostedUsageModelBreakdown */
        V2HostedUsageModelBreakdown: {
            /** Model */
            model: string;
            /** Provider */
            provider?: string | null;
            /** Credits */
            credits: number;
            /** Requests */
            requests: number;
        };
        /** V2HostedUsageSummaryResponse */
        V2HostedUsageSummaryResponse: {
            /** Period Start */
            period_start: string;
            /** Period End */
            period_end: string;
            /** Total Credits */
            total_credits: number;
            /** Total Requests */
            total_requests: number;
            /** By Model */
            by_model: components["schemas"]["V2HostedUsageModelBreakdown"][];
            /** By Day */
            by_day: components["schemas"]["V2HostedUsageDay"][];
        };
        /** V2PlanResponse */
        V2PlanResponse: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Price Cents */
            price_cents: number;
            /** Points Per Usd */
            points_per_usd: number;
            /**
             * Signup Grant Credits
             * @default 0
             */
            signup_grant_credits: number;
            /**
             * Subscription Grant Credits
             * @default 0
             */
            subscription_grant_credits: number;
            /** Vcpu */
            vcpu: number;
            /** Ram Gb */
            ram_gb: number;
            /** Disk Size */
            disk_size: number;
            /** Instance Type */
            instance_type?: string | null;
            /** Offers */
            offers?: components["schemas"]["V2BillingOfferResponse"][];
        };
        /** V2PortalResponse */
        V2PortalResponse: {
            /** Url */
            url: string;
            /** Portal Url */
            portal_url: string;
            /** Status */
            status?: string | null;
            /** Redirect Url */
            redirect_url?: string | null;
            /** Payment Intent Client Secret */
            payment_intent_client_secret?: string | null;
            /** Message */
            message?: string | null;
            /** Effective At */
            effective_at?: string | null;
            /** Amount Due Usd */
            amount_due_usd?: number | null;
        };
        /** V2RebindAgentAiProviderRequest */
        V2RebindAgentAiProviderRequest: {
            /** Primary Model */
            primary_model?: string | components["schemas"]["V2AiProviderPrimaryModelRef"] | null;
            /** Ai Provider Id */
            ai_provider_id?: string | null;
            /** Provider Ids */
            provider_ids?: string[];
            /**
             * Ai Provider Auth Kind
             * @enum {string}
             */
            ai_provider_auth_kind: "unmanaged" | "managed" | "api_key" | "codex_oauth";
            /** Ai Provider Bootstrap */
            ai_provider_bootstrap?: {
                [key: string]: unknown;
            } | null;
        };
        /** V2SetAgentEnabledRequest */
        V2SetAgentEnabledRequest: {
            /** Enabled */
            enabled: boolean;
            /** Language */
            language?: ("en" | "es" | "fr" | "de" | "ja" | "ko" | "pt" | "zh-CN" | "zh-TW") | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** V2UpdateDeploymentRequest */
        V2UpdateDeploymentRequest: {
            /** Assistant Name */
            assistant_name?: string | null;
            /** Name */
            name?: string | null;
            /** Runtime */
            runtime?: ("openclaw" | "hermes") | null;
        };
        /** V2WalletAutoReloadActionResponse */
        V2WalletAutoReloadActionResponse: {
            /** Attempt Id */
            attempt_id: number;
            /** Payment Intent Id */
            payment_intent_id: string;
            /** Client Secret */
            client_secret: string;
            /** Error Code */
            error_code?: string | null;
        };
        /** V2WalletAutoReloadRequest */
        V2WalletAutoReloadRequest: {
            /** Payment Mode */
            payment_mode?: "card" | null;
            /** Auto Reload Enabled */
            auto_reload_enabled?: boolean | null;
            /** Auto Reload Threshold Credits */
            auto_reload_threshold_credits?: number | string | null;
            /** Auto Reload Amount Cents */
            auto_reload_amount_cents?: number | null;
            /** Auto Reload Monthly Cap Cents */
            auto_reload_monthly_cap_cents?: number | null;
        };
        /** V2WalletLedgerItemResponse */
        V2WalletLedgerItemResponse: {
            /** Id */
            id: string;
            /** Operation */
            operation: string;
            /** Request Id */
            request_id: string;
            /** Credits Amount */
            credits_amount: number;
            /** Status */
            status: string;
            /** Notes */
            notes?: string | null;
            /** Created At */
            created_at: string;
            /** Applied At */
            applied_at?: string | null;
        };
        /** V2WalletLedgerResponse */
        V2WalletLedgerResponse: {
            /** Items */
            items: components["schemas"]["V2WalletLedgerItemResponse"][];
            /** Has More */
            has_more: boolean;
        };
        /** V2WalletResponse */
        V2WalletResponse: {
            /** Balance Credits */
            balance_credits: number;
            /** Overdraft Credits */
            overdraft_credits: number;
            /** Balance Snapshot At */
            balance_snapshot_at?: string | null;
            /**
             * Payment Mode
             * @constant
             */
            payment_mode: "card";
            /** X402 Enabled */
            x402_enabled: boolean;
            /** Auto Reload Enabled */
            auto_reload_enabled: boolean;
            /** Auto Reload Threshold Credits */
            auto_reload_threshold_credits: number;
            /** Auto Reload Amount Cents */
            auto_reload_amount_cents: number;
            /** Auto Reload Monthly Cap Cents */
            auto_reload_monthly_cap_cents: number;
            auto_reload_action?: components["schemas"]["V2WalletAutoReloadActionResponse"] | null;
            /** Points Per Usd */
            points_per_usd: number;
        };
        /** V2WalletTopupRequest */
        V2WalletTopupRequest: {
            /** Amount Cents */
            amount_cents: number;
            /** Locale */
            locale?: string | null;
        };
        /** V2WalletTopupResponse */
        V2WalletTopupResponse: {
            /** Status */
            status: string;
            /** Flow Type */
            flow_type?: string | null;
            /** Payment Intent Id */
            payment_intent_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
            /** Credits Added */
            credits_added?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_v1_agent_environments_v1_agent_environments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V1AgentEnvironmentsResponse"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V1UserResponse"];
                };
            };
        };
    };
    list_v2_deployments_v2_deployments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"][];
                };
            };
        };
    };
    create_v2_deployment_v2_deployments_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2HostedDeployRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_v2_deploy_request_status_v2_deployments_by_request__deploy_request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deploy_request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeployRequestStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_v2_deployment_v2_deployments__deployment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_v2_deployment_v2_deployments__deployment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2DeploymentDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_v2_deployment_v2_deployments__deployment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2UpdateDeploymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_v2_agent_enabled_v2_deployments__deployment_id__agents__agent_type__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_type: "openclaw" | "hermes";
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2SetAgentEnabledRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebind_v2_agent_ai_provider_v2_deployments__deployment_id__agents__agent_type__ai_provider_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_type: "openclaw" | "hermes";
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2RebindAgentAiProviderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_v2_deployment_terminal_session_v2_deployments__deployment_id__terminal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2DeploymentTerminalSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_v2_deployment_runtime_ui_redemption_v2_deployments__deployment_id__runtime_ui_redemption_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2DeploymentRuntimeUiRedemptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_v2_deployment_v2_deployments__deployment_id__restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2DeploymentLifecycleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_v2_deployment_v2_deployments__deployment_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2DeploymentLifecycleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_v2_deployment_v2_deployments__deployment_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2DeploymentLifecycleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkout_v2_subscription_v2_subscription_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ComputeCheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_v2_subscription_v2_subscription_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ComputeSubscriptionCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ComputeSubscriptionActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fix_payment_v2_subscription_v2_subscription_fix_payment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["V2ComputeFixPaymentRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2PortalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_v2_subscription_billing_history_v2_subscription_billing_history_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ComputeBillingHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_v2_subscription_plan_v2_subscription_plan_change_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ComputePlanChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ComputePlanChangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_v2_subscription_plan_change_v2_subscription_plan_quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ComputePlanChangeQuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ComputePlanChangeQuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_v2_subscription_plans_v2_subscription_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2PlanResponse"][];
                };
            };
        };
    };
    portal_v2_subscription_v2_subscription_portal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["V2ComputePortalRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2PortalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_v2_subscription_v2_subscription_quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ComputeSubscriptionQuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ComputeSubscriptionQuoteResponse-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_v2_subscription_v2_subscription_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ComputeSubscriptionResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ComputeSubscriptionActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hosted_v2_usage_summary_v2_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedUsageSummaryResponse"];
                };
            };
        };
    };
    get_wallet_v2_wallet_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2WalletResponse"];
                };
            };
        };
    };
    update_wallet_auto_reload_v2_wallet_auto_reload_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2WalletAutoReloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2WalletResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_v2_wallet_ledger_v2_wallet_ledger_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2WalletLedgerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_wallet_topup_v2_wallet_topup_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2WalletTopupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2WalletTopupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
