/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List V2 Deployments */
        get: operations["list_v2_deployments_v2_deployments_get"];
        put?: never;
        /** Create V2 Deployment */
        post: operations["create_v2_deployment_v2_deployments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deployments/{deployment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get V2 Deployment */
        get: operations["get_v2_deployment_v2_deployments__deployment_id__get"];
        put?: never;
        post?: never;
        /** Delete V2 Deployment */
        delete: operations["delete_v2_deployment_v2_deployments__deployment_id__delete"];
        options?: never;
        head?: never;
        /** Update V2 Deployment */
        patch: operations["update_v2_deployment_v2_deployments__deployment_id__patch"];
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/agents/{agent_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set V2 Agent Enabled */
        patch: operations["set_v2_agent_enabled_v2_deployments__deployment_id__agents__agent_type__patch"];
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/agents/{agent_type}/ai-provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rebind V2 Agent Ai Provider */
        patch: operations["rebind_v2_agent_ai_provider_v2_deployments__deployment_id__agents__agent_type__ai_provider_patch"];
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/onboard-agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Onboard V2 Agent */
        post: operations["onboard_v2_agent_v2_deployments__deployment_id__onboard_agent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart V2 Deployment */
        post: operations["restart_v2_deployment_v2_deployments__deployment_id__restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start V2 Deployment */
        post: operations["start_v2_deployment_v2_deployments__deployment_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deployments/{deployment_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop V2 Deployment */
        post: operations["stop_v2_deployment_v2_deployments__deployment_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/activation-fee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V2 Activation Fee Status */
        get: operations["v2_activation_fee_status_v2_subscription_activation_fee_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkout V2 Subscription */
        post: operations["checkout_v2_subscription_v2_subscription_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current V2 Subscription */
        get: operations["current_v2_subscription_v2_subscription_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List V2 Subscription Plans */
        get: operations["list_v2_subscription_plans_v2_subscription_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/subscription/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Portal V2 Subscription */
        post: operations["portal_v2_subscription_v2_subscription_portal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hosted V2 Usage Summary */
        get: operations["hosted_v2_usage_summary_v2_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wallet */
        get: operations["get_wallet_v2_wallet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/wallet/auto-reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Wallet Auto Reload */
        put: operations["update_wallet_auto_reload_v2_wallet_auto_reload_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/wallet/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List V2 Wallet Ledger */
        get: operations["list_v2_wallet_ledger_v2_wallet_ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/wallet/topup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Wallet Topup */
        post: operations["create_wallet_topup_v2_wallet_topup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** V1UserFeatureResolution */
        V1UserFeatureResolution: {
            /** Enabled */
            enabled: boolean;
            source: components["schemas"]["V1UserFeatureResolutionSource"];
        };
        /**
         * V1UserFeatureResolutionSource
         * @enum {string}
         */
        V1UserFeatureResolutionSource: "default" | "rule_user_id" | "rule_clerk_id" | "rule_email" | "rule_email_domain" | "rule_referral_l1";
        /** V1UserProductCapabilities */
        V1UserProductCapabilities: {
            /**
             * Can Use V1
             * @default true
             */
            can_use_v1: boolean;
            /**
             * Can Use V2
             * @default false
             */
            can_use_v2: boolean;
        };
        /** V1UserResponse */
        V1UserResponse: {
            /**
             * Id
             * Format: sqid
             * @example usr_K8fJ3pQm
             */
            id: string;
            /** Clerk Id */
            clerk_id: string;
            /** Email */
            email: string | null;
            /** Name */
            name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Settings */
            settings: {
                [key: string]: components["schemas"]["V1UserFeatureResolution"];
            };
            /** Evm Wallet Address */
            evm_wallet_address?: string | null;
            capabilities: components["schemas"]["V1UserProductCapabilities"];
        };
        /** V2ActivationFeeStatusResponse */
        V2ActivationFeeStatusResponse: {
            /**
             * Amount Cents
             * @default 0
             */
            amount_cents: number;
            /**
             * Satisfied
             * @default false
             */
            satisfied: boolean;
        };
        /** V2AiProviderBindingInfo */
        V2AiProviderBindingInfo: {
            /** Provider Id */
            provider_id: string;
            /**
             * Auth Kind
             * @enum {string}
             */
            auth_kind: "managed" | "api_key" | "codex_oauth";
            /** Primary Model */
            primary_model?: string | null;
        };
        /** V2BillingOfferResponse */
        V2BillingOfferResponse: {
            /** Billing Term Months */
            billing_term_months: number;
            /** Price Cents */
            price_cents: number;
            /** Effective Monthly Price Cents */
            effective_monthly_price_cents: number;
            /** Discount Percent */
            discount_percent: number;
        };
        /** V2CheckoutResponse */
        V2CheckoutResponse: {
            /**
             * Flow Type
             * @default checkout_session
             */
            flow_type: string;
            /** Action Url */
            action_url?: string | null;
            /**
             * Checkout Url
             * @default
             */
            checkout_url: string;
            /** Client Secret */
            client_secret?: string | null;
        };
        /** V2ComputeCheckoutRequest */
        V2ComputeCheckoutRequest: {
            /** Plan Slug */
            plan_slug: string;
            /**
             * Billing Term Months
             * @default 1
             */
            billing_term_months: number;
            deploy_config?: components["schemas"]["V2HostedDeployRequest"] | null;
            /** Upgrade Deployment Id */
            upgrade_deployment_id?: string | null;
            /**
             * Ui Mode
             * @default hosted
             */
            ui_mode: string;
            /** Locale */
            locale?: string | null;
        };
        /** V2ComputePortalRequest */
        V2ComputePortalRequest: {
            /** Locale */
            locale?: string | null;
        };
        /** V2DeploymentDeleteResponse */
        V2DeploymentDeleteResponse: {
            /** Status */
            status: string;
            /** Cvm Deleted */
            cvm_deleted: boolean;
        };
        /** V2DeploymentLifecycleResponse */
        V2DeploymentLifecycleResponse: {
            /** Status */
            status: string;
            /** Upgrade Task Id */
            upgrade_task_id?: string | null;
            /** Upgrade Status */
            upgrade_status?: string | null;
        };
        /** V2HostedConfigRequest */
        V2HostedConfigRequest: {
            /** Primary Model */
            primary_model?: string | null;
            /** Channel */
            channel?: string | null;
            /** Telegram Bot Token */
            telegram_bot_token?: string | null;
            /** Telegram Allowed Usernames */
            telegram_allowed_usernames?: string[] | null;
            /** Discord Bot Token */
            discord_bot_token?: string | null;
            /** Discord Guild Id */
            discord_guild_id?: string | null;
            /** Slack Bot Token */
            slack_bot_token?: string | null;
            /** Slack App Token */
            slack_app_token?: string | null;
            /** Assistant Name */
            assistant_name?: string | null;
            /** Personality */
            personality?: string | null;
            /** Language */
            language?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Public Ports */
            public_ports?: number[] | null;
            /**
             * Enable Openclaw
             * @default true
             */
            enable_openclaw: boolean;
            /**
             * Enable Hermes
             * @default false
             */
            enable_hermes: boolean;
        };
        /** V2HostedDeployRequest */
        V2HostedDeployRequest: {
            /**
             * Compute Plan Slug
             * @enum {string}
             */
            compute_plan_slug: "compute_free" | "compute_performance";
            /** Primary Model */
            primary_model?: string | null;
            /** Channel */
            channel?: string | null;
            /** Telegram Bot Token */
            telegram_bot_token?: string | null;
            /** Telegram Allowed Usernames */
            telegram_allowed_usernames?: string[] | null;
            /** Discord Bot Token */
            discord_bot_token?: string | null;
            /** Discord Guild Id */
            discord_guild_id?: string | null;
            /** Slack Bot Token */
            slack_bot_token?: string | null;
            /** Slack App Token */
            slack_app_token?: string | null;
            /** Model */
            model?: string | null;
            /** Assistant Name */
            assistant_name?: string | null;
            /** Personality */
            personality?: string | null;
            /** Language */
            language?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Public Ports */
            public_ports?: number[] | null;
            /** Enable Openclaw */
            enable_openclaw?: boolean | null;
            /**
             * Enable Hermes
             * @default false
             */
            enable_hermes: boolean;
            /** Deploy Request Id */
            deploy_request_id?: string | null;
            /** Ai Provider Id */
            ai_provider_id?: string | null;
            /** Ai Provider Auth Kind */
            ai_provider_auth_kind?: ("managed" | "api_key" | "codex_oauth") | null;
            /** Ai Provider Bootstrap */
            ai_provider_bootstrap?: {
                [key: string]: unknown;
            } | null;
            config?: components["schemas"]["V2HostedConfigRequest"] | null;
        };
        /** V2HostedDeploymentDetailsInfo */
        V2HostedDeploymentDetailsInfo: {
            /**
             * Compute Plan Slug
             * @enum {string}
             */
            compute_plan_slug: "compute_free" | "compute_performance";
            /**
             * Mux Enabled
             * @default false
             */
            mux_enabled: boolean;
            /**
             * Telegram Mux Enabled
             * @default false
             */
            telegram_mux_enabled: boolean;
            /**
             * Discord Mux Enabled
             * @default false
             */
            discord_mux_enabled: boolean;
            /**
             * Whatsapp Mux Enabled
             * @default false
             */
            whatsapp_mux_enabled: boolean;
            /**
             * Imessage Mux Enabled
             * @default false
             */
            imessage_mux_enabled: boolean;
            /**
             * Kobb Available
             * @default false
             */
            kobb_available: boolean;
            /** Channel */
            channel?: string | null;
            /** Primary Model */
            primary_model?: string | null;
            /** Ai Provider Id */
            ai_provider_id?: string | null;
            /**
             * Ai Provider Auth Kind
             * @default managed
             * @enum {string}
             */
            ai_provider_auth_kind: "managed" | "api_key" | "codex_oauth";
            /** Ai Provider Bindings */
            ai_provider_bindings?: {
                [key: string]: components["schemas"]["V2AiProviderBindingInfo"];
            };
            /** Telegram Allowed Usernames */
            telegram_allowed_usernames?: string[] | null;
            /** Telegram Bot Username */
            telegram_bot_username?: string | null;
            /** Telegram Entry Url */
            telegram_entry_url?: string | null;
            /** Telegram Provider */
            telegram_provider?: string | null;
            /** Discord Guild Id */
            discord_guild_id?: string | null;
            /** Public Ports */
            public_ports?: number[];
            /**
             * Enable Openclaw
             * @default true
             */
            enable_openclaw: boolean;
            /**
             * Enable Hermes
             * @default false
             */
            enable_hermes: boolean;
            /** Onboarded Agents */
            onboarded_agents?: string[];
            /** Configured Agents */
            configured_agents?: string[];
            /** Clawdi Cloud Environments */
            clawdi_cloud_environments?: {
                [key: string]: string;
            };
            /** Vcpu */
            vcpu?: number | null;
            /** Ram Gb */
            ram_gb?: number | null;
            /** Disk Gb */
            disk_gb?: number | null;
        };
        /** V2HostedDeploymentResponse */
        V2HostedDeploymentResponse: {
            /**
             * Id
             * Format: sqid
             * @example hdep_K8fJ3pQm
             */
            id: string;
            /**
             * User Id
             * Format: sqid
             * @example usr_K8fJ3pQm
             */
            user_id: string;
            /** Name */
            name: string;
            /** App Id */
            app_id: string;
            /** Backend */
            backend?: string | null;
            /**
             * Status
             * @default unknown
             */
            status: string;
            /** Endpoints */
            endpoints?: string[];
            /** Gateway Token */
            gateway_token?: string | null;
            /** Ui Access Token */
            ui_access_token?: string | null;
            /** Openclaw Ui Url */
            openclaw_ui_url?: string | null;
            /** Hermes Ui Url */
            hermes_ui_url?: string | null;
            config_info?: components["schemas"]["V2HostedDeploymentDetailsInfo"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Upgrade Available
             * @default false
             */
            upgrade_available: boolean;
            /** Agent Version */
            agent_version?: string | null;
            /** App Image */
            app_image?: string | null;
        };
        /** V2HostedUsageDay */
        V2HostedUsageDay: {
            /** Date */
            date: string;
            /** Credits */
            credits: number;
        };
        /** V2HostedUsageModelBreakdown */
        V2HostedUsageModelBreakdown: {
            /** Model */
            model: string;
            /** Provider */
            provider?: string | null;
            /** Credits */
            credits: number;
            /** Requests */
            requests: number;
        };
        /** V2HostedUsageSummaryResponse */
        V2HostedUsageSummaryResponse: {
            /** Period Start */
            period_start: string;
            /** Period End */
            period_end: string;
            /** Total Credits */
            total_credits: number;
            /** Total Requests */
            total_requests: number;
            /** By Model */
            by_model: components["schemas"]["V2HostedUsageModelBreakdown"][];
            /** By Day */
            by_day: components["schemas"]["V2HostedUsageDay"][];
        };
        /** V2OnboardAgentRequest */
        V2OnboardAgentRequest: {
            /**
             * Agent Type
             * @enum {string}
             */
            agent_type: "openclaw" | "hermes";
            /** Primary Model */
            primary_model?: string | null;
            /** Assistant Name */
            assistant_name?: string | null;
            /** Personality */
            personality?: string | null;
            /** Language */
            language?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Ai Provider Id */
            ai_provider_id?: string | null;
            /** Ai Provider Auth Kind */
            ai_provider_auth_kind?: ("managed" | "api_key" | "codex_oauth") | null;
            /** Ai Provider Bootstrap */
            ai_provider_bootstrap?: {
                [key: string]: unknown;
            } | null;
        };
        /** V2PlanResponse */
        V2PlanResponse: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Price Cents */
            price_cents: number;
            /** Monthly Budget Credits */
            monthly_budget_credits: number;
            /** Points Per Usd */
            points_per_usd: number;
            /** Vcpu */
            vcpu: number;
            /** Ram Gb */
            ram_gb: number;
            /** Disk Size */
            disk_size: number;
            /** Instance Type */
            instance_type?: string | null;
            /** Offers */
            offers?: components["schemas"]["V2BillingOfferResponse"][];
        };
        /** V2PortalResponse */
        V2PortalResponse: {
            /** Url */
            url: string;
            /** Portal Url */
            portal_url: string;
            /** Status */
            status?: string | null;
            /** Redirect Url */
            redirect_url?: string | null;
            /** Payment Intent Client Secret */
            payment_intent_client_secret?: string | null;
            /** Message */
            message?: string | null;
            /** Effective At */
            effective_at?: string | null;
            /** Amount Due Usd */
            amount_due_usd?: number | null;
        };
        /** V2RebindAgentAiProviderRequest */
        V2RebindAgentAiProviderRequest: {
            /** Primary Model */
            primary_model?: string | null;
            /** Ai Provider Id */
            ai_provider_id?: string | null;
            /**
             * Ai Provider Auth Kind
             * @enum {string}
             */
            ai_provider_auth_kind: "managed" | "api_key" | "codex_oauth";
            /** Ai Provider Bootstrap */
            ai_provider_bootstrap?: {
                [key: string]: unknown;
            } | null;
        };
        /** V2SetAgentEnabledRequest */
        V2SetAgentEnabledRequest: {
            /** Enabled */
            enabled: boolean;
            /** Personality */
            personality?: string | null;
            /** Language */
            language?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** V2SubscriptionResponse */
        V2SubscriptionResponse: {
            /**
             * Id
             * Format: sqid
             * @example sub_K8fJ3pQm
             */
            id: string;
            /** Plan Slug */
            plan_slug: string;
            /** Payment Provider */
            payment_provider?: string | null;
            /** Status */
            status: string;
            /** Current Period Start */
            current_period_start: string | null;
            /** Current Period End */
            current_period_end: string | null;
            /** Budget Credits Total */
            budget_credits_total: number;
            /** Budget Credits Used */
            budget_credits_used?: number;
            /** Addon Credits Remaining */
            addon_credits_remaining: number;
            /** Points Per Usd */
            points_per_usd: number;
            /**
             * Use Addon Credits
             * @default true
             */
            use_addon_credits: boolean;
            /** Cancel At Period End */
            cancel_at_period_end: boolean;
            /**
             * Billing Term Months
             * @default 1
             */
            billing_term_months: number;
            /** Billing Price Cents Snapshot */
            billing_price_cents_snapshot?: number | null;
            /** Pending Billing Term Months */
            pending_billing_term_months?: number | null;
            /** Pending Billing Term Effective At */
            pending_billing_term_effective_at?: string | null;
            /** Pending Downgrade Plan Slug */
            pending_downgrade_plan_slug?: string | null;
            /** Pending Downgrade Effective At */
            pending_downgrade_effective_at?: string | null;
            /**
             * Card On File
             * @default false
             */
            card_on_file: boolean;
            /**
             * Card Setup Required
             * @default false
             */
            card_setup_required: boolean;
            /** Card Brand */
            card_brand?: string | null;
            /** Card Last4 */
            card_last4?: string | null;
            /** Card Exp Month */
            card_exp_month?: number | null;
            /** Card Exp Year */
            card_exp_year?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Collection Method
             * @default charge_automatically
             */
            collection_method: string;
            /**
             * Entitled
             * @default true
             */
            entitled: boolean;
            /**
             * Activation Fee Amount Cents
             * @default 0
             */
            activation_fee_amount_cents: number;
            /**
             * Activation Fee Satisfied
             * @default false
             */
            activation_fee_satisfied: boolean;
            /** Pending Collection Method */
            pending_collection_method?: string | null;
            /** Pending Collection Method Effective At */
            pending_collection_method_effective_at?: string | null;
            /** Entitled Until */
            entitled_until?: string | null;
            /** Contract Source */
            contract_source?: string | null;
            /** Prepaid Ends At */
            prepaid_ends_at?: string | null;
            /** Allowance Period Start */
            allowance_period_start?: string | null;
            /** Allowance Period End */
            allowance_period_end?: string | null;
            /** Next Allowance Reset At */
            next_allowance_reset_at?: string | null;
        };
        /** V2UpdateDeploymentRequest */
        V2UpdateDeploymentRequest: {
            /** Assistant Name */
            assistant_name?: string | null;
            /** Name */
            name?: string | null;
        };
        /** V2WalletAutoReloadActionResponse */
        V2WalletAutoReloadActionResponse: {
            /** Attempt Id */
            attempt_id: number;
            /** Payment Intent Id */
            payment_intent_id: string;
            /** Client Secret */
            client_secret: string;
            /** Error Code */
            error_code?: string | null;
        };
        /** V2WalletAutoReloadRequest */
        V2WalletAutoReloadRequest: {
            /** Payment Mode */
            payment_mode?: "card" | null;
            /** Auto Reload Enabled */
            auto_reload_enabled?: boolean | null;
            /** Auto Reload Threshold Credits */
            auto_reload_threshold_credits?: number | string | null;
            /** Auto Reload Amount Cents */
            auto_reload_amount_cents?: number | null;
            /** Auto Reload Monthly Cap Cents */
            auto_reload_monthly_cap_cents?: number | null;
        };
        /** V2WalletLedgerItemResponse */
        V2WalletLedgerItemResponse: {
            /** Id */
            id: string;
            /** Operation */
            operation: string;
            /** Request Id */
            request_id: string;
            /** Credits Amount */
            credits_amount: number;
            /** Status */
            status: string;
            /** Notes */
            notes?: string | null;
            /** Created At */
            created_at: string;
            /** Applied At */
            applied_at?: string | null;
        };
        /** V2WalletLedgerResponse */
        V2WalletLedgerResponse: {
            /** Items */
            items: components["schemas"]["V2WalletLedgerItemResponse"][];
        };
        /** V2WalletResponse */
        V2WalletResponse: {
            /** Balance Credits */
            balance_credits: number;
            /** Balance Snapshot At */
            balance_snapshot_at?: string | null;
            /**
             * Payment Mode
             * @constant
             */
            payment_mode: "card";
            /** Auto Reload Enabled */
            auto_reload_enabled: boolean;
            /** Auto Reload Threshold Credits */
            auto_reload_threshold_credits: number;
            /** Auto Reload Amount Cents */
            auto_reload_amount_cents: number;
            /** Auto Reload Monthly Cap Cents */
            auto_reload_monthly_cap_cents: number;
            auto_reload_action?: components["schemas"]["V2WalletAutoReloadActionResponse"] | null;
            /** Points Per Usd */
            points_per_usd: number;
        };
        /** V2WalletTopupRequest */
        V2WalletTopupRequest: {
            /** Amount Cents */
            amount_cents: number;
            /** Locale */
            locale?: string | null;
        };
        /** V2WalletTopupResponse */
        V2WalletTopupResponse: {
            /** Status */
            status: string;
            /** Flow Type */
            flow_type?: string | null;
            /** Payment Intent Id */
            payment_intent_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
            /** Credits Added */
            credits_added?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V1UserResponse"];
                };
            };
        };
    };
    list_v2_deployments_v2_deployments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"][];
                };
            };
        };
    };
    create_v2_deployment_v2_deployments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2HostedDeployRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_v2_deployment_v2_deployments__deployment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_v2_deployment_v2_deployments__deployment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2DeploymentDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_v2_deployment_v2_deployments__deployment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2UpdateDeploymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_v2_agent_enabled_v2_deployments__deployment_id__agents__agent_type__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_type: "openclaw" | "hermes";
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2SetAgentEnabledRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebind_v2_agent_ai_provider_v2_deployments__deployment_id__agents__agent_type__ai_provider_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_type: "openclaw" | "hermes";
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2RebindAgentAiProviderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    onboard_v2_agent_v2_deployments__deployment_id__onboard_agent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2OnboardAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedDeploymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_v2_deployment_v2_deployments__deployment_id__restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2DeploymentLifecycleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_v2_deployment_v2_deployments__deployment_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2DeploymentLifecycleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_v2_deployment_v2_deployments__deployment_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2DeploymentLifecycleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    v2_activation_fee_status_v2_subscription_activation_fee_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ActivationFeeStatusResponse"];
                };
            };
        };
    };
    checkout_v2_subscription_v2_subscription_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ComputeCheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_v2_subscription_v2_subscription_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2SubscriptionResponse"] | null;
                };
            };
        };
    };
    list_v2_subscription_plans_v2_subscription_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2PlanResponse"][];
                };
            };
        };
    };
    portal_v2_subscription_v2_subscription_portal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["V2ComputePortalRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2PortalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hosted_v2_usage_summary_v2_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2HostedUsageSummaryResponse"];
                };
            };
        };
    };
    get_wallet_v2_wallet_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2WalletResponse"];
                };
            };
        };
    };
    update_wallet_auto_reload_v2_wallet_auto_reload_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2WalletAutoReloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2WalletResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_v2_wallet_ledger_v2_wallet_ledger_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2WalletLedgerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_wallet_topup_v2_wallet_topup_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2WalletTopupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2WalletTopupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
