export const GENERATED_RUNTIME_SYSTEMD_FILE_HEADER =
	"# Generated by clawdi runtime init. Do not edit inside hosted runtime.";

export function isGeneratedRuntimeSystemdFile(contents: string): boolean {
	return contents.startsWith(GENERATED_RUNTIME_SYSTEMD_FILE_HEADER);
}

export function runtimeUserName(): string {
	return process.env.CLAWDI_RUNTIME_USER?.trim() || "clawdi";
}

export function runtimeUserSystemdEnvironment(uid: string): Record<string, string> {
	const runtimeDir = `/run/user/${uid}`;
	return {
		XDG_RUNTIME_DIR: runtimeDir,
		DBUS_SESSION_BUS_ADDRESS: `unix:path=${runtimeDir}/bus`,
	};
}
