import type { RuntimePaths } from "./paths";

export const GENERATED_RUNTIME_SYSTEMD_FILE_HEADER =
	"# Generated by clawdi runtime init. Do not edit inside hosted runtime.";

export function isGeneratedRuntimeSystemdFile(contents: string): boolean {
	return contents.startsWith(GENERATED_RUNTIME_SYSTEMD_FILE_HEADER);
}

export function runtimeUserName(): string {
	return process.env.CLAWDI_RUNTIME_USER?.trim() || "clawdi";
}

export function runtimeUserSystemdEnvironment(
	paths: RuntimePaths,
	runtimeUser: string,
	uid: string,
): Record<string, string> {
	const runtimeDir = `/run/user/${uid}`;
	return {
		HOME: paths.userHome,
		USER: runtimeUser,
		LOGNAME: runtimeUser,
		XDG_RUNTIME_DIR: runtimeDir,
		DBUS_SESSION_BUS_ADDRESS: `unix:path=${runtimeDir}/bus`,
	};
}

export function runtimeUserSystemdEnvArgs(
	paths: RuntimePaths,
	runtimeUser: string,
	uid: string,
): string[] {
	return Object.entries(runtimeUserSystemdEnvironment(paths, runtimeUser, uid)).map(
		([key, value]) => `${key}=${value}`,
	);
}
