export const agentSurfaceCopy = {
	aIProviders: "AI Providers",
	aIProviders2: "AI providers",
	activity: "Activity",
	addACustomTelegramDiscordOrWhatsapp:
		"Add a Custom Telegram, Discord, or WhatsApp account you manage.",
	agentSoftware: "Agent software",
	agents: "Agents",
	askYourAgentToSetUpClawdi: "Ask your agent to set up Clawdi",
	avatar: "Avatar",
	channels: "Channels",
	clawdi: "Clawdi",
	commands: "Commands",
	compute: "Compute",
	connectAProviderToUseYourOwn: "Connect a provider to use your own model access with agents.",
	connectAnAgentToSeeItHere: "Connect an Agent to see it here.",
	couldnTLoadClawdiBots: "Couldn't load Clawdi bots",
	couldnTLoadAgent: "Couldn't load agent",
	couldnTLoadAgents: "Couldn't load agents",
	couldnTLoadChannelHealth: "Couldn't load channel health",
	couldnTLoadChannels: "Couldn't load channels",
	couldnTLoadSyncedSkills: "Couldn't load synced Skills",
	couldnTLoadProviders: "Couldn\u2019t load providers",
	default: "Default",
	deployAnAgent: "Deploy an Agent",
	deployFirstThenConfigureModelAccessInside:
		"Deploy first, then configure model access inside the Agent.",
	disconnect: "Disconnect",
	everyAgentInYourAccount: "Every Agent in your account.",
	gitHubSkillRepository: "GitHub Skill repository",
	health: "Health",
	imageUpTo2Mb: "Image up to 2 MB.",
	installOnTheAgent: "Install on the Agent",
	installSkill: "Install skill",
	name: "Name",
	noAgentsYet: "No Agents yet",
	noSkillsHaveSyncedFromThisAgent:
		"No Skills have synced from this Agent yet. Install one with the CLI, then sync the Agent.",
	noBotsYet: "No bots yet",
	noPluginsFound: "No plugins found",
	noProvidersAdded: "No providers added",
	noSetupRequiredUsageDrawsFromYour: "No setup required. Usage draws from your Wallet.",
	nodeJs24IsRequired: "Node.js 24+ is required.",
	personalize: "Personalize",
	plugins: "Plugins",
	recommended: "Recommended",
	searchPlugins: "Search plugins\u2026",
	setupPrompt: "Setup prompt",
	shownInTheSidebarPickersAndAgent: "Shown in the sidebar, pickers, and agent lists.",
	status: "Status",
	stopThisInstallationWhileKeepingItsClawdi:
		"Stop this installation while keeping its Clawdi data.",
	tryADifferentSearchOrCategory: "Try a different search or category.",
	uninstallSkill: "Uninstall skill",
	useAShortNameThatDistinguishesThis: "Use a short name that distinguishes this agent from others.",
	ownerRepoOrOwnerRepoPathTo: "owner/repo or owner/repo/path-to-skill\u2026",
} as const;
