export const agentSurfaceCopy = {
	aIProviders: "AI Providers",
	aIProviders2: "AI providers",
	activity: "Activity",
	addACustomTelegramDiscordOrWhatsapp:
		"Add a Custom Telegram, Discord, or WhatsApp account you manage.",
	agentSoftware: "Agent software",
	agents: "Agents",
	askYourAgentToSetUpClawdi: "Ask your agent to set up Clawdi",
	avatar: "Avatar",
	channels: "Channels",
	clawdi: "Clawdi",
	commands: "Commands",
	compute: "Compute",
	connectAProviderToUseYourOwn: "Connect a provider to use your own model access with agents.",
	connectAnAgentToSeeItHere: "Connect an agent to see it here.",
	couldnTLoadClawdiBots: "Couldn't load Clawdi bots",
	couldnTLoadAgent: "Couldn't load agent",
	couldnTLoadAgents: "Couldn't load agents",
	couldnTLoadChannelHealth: "Couldn't load channel health",
	couldnTLoadChannels: "Couldn't load channels",
	couldnTLoadSyncedSkills: "Couldn't load synced skills",
	couldnTLoadProviders: "Couldn\u2019t load providers",
	default: "Default",
	deployAnAgent: "Deploy an Agent",
	deployFirstThenConfigureModelAccessInside:
		"Deploy first, then configure model access inside the agent.",
	disconnect: "Disconnect",
	everyAgentInYourAccount: "Every agent in your account.",
	gitHubSkillRepository: "GitHub skill repository",
	health: "Health",
	imageUpTo2Mb: "Image up to 2 MB.",
	installOnTheAgent: "Install on the agent",
	installSkill: "Install skill",
	name: "Name",
	noAgentsYet: "No agents yet",
	noSkillsHaveSyncedFromThisAgent:
		"No skills have synced from this agent yet. Install one with the CLI, then sync the agent.",
	noBotsYet: "No bots yet",
	noPluginsFound: "No plugins found",
	noProvidersAdded: "No providers added",
	noSetupRequiredUsageDrawsFromYour: "No setup required. Usage draws from your wallet.",
	installationHint: "Windows or package-manager users? See",
	installationLink: "installation",
	personalize: "Personalize",
	plugins: "Plugins",
	recommended: "Recommended",
	searchPlugins: "Search plugins\u2026",
	setupPrompt: "Setup prompt",
	shownInTheSidebarPickersAndAgent: "Shown in the sidebar, pickers, and agent lists.",
	status: "Status",
	stopThisInstallationWhileKeepingItsClawdi:
		"Stop this installation while keeping its Clawdi data.",
	tryADifferentSearchOrCategory: "Try a different search or category.",
	uninstallSkill: "Uninstall skill",
	useAShortNameThatDistinguishesThis: "Use a short name that distinguishes this agent from others.",
	ownerRepoOrOwnerRepoPathTo: "owner/repo or owner/repo/path-to-skill\u2026",
	readOnly: "Read-only",
	unavailable: "Unavailable",
	couldnTUpdatePlugin: "Couldn't update plugin",
	installed: "Installed",
	available: "Available",
	thisPluginIsNoLongerAvailableInTheStore: "This plugin is no longer available in the Store.",
	customUpload: "Custom upload",
	syncStopsAndRetainedSessionsSkillsFilesAndProjects:
		"Sync stops and retained sessions, skills, files, and projects stay in your account.",
	disconnectAgent: "Disconnect agent",
	chooseHowYourAgentsReachAModel: "Choose how your agents reach a model.",
	yourProviders: "Your providers",
	addACredentialBeforeAssigningThisProviderToAn:
		"Add a credential before assigning this provider to an agent.",
	finishSetupBeforeAssigningThisProviderToAnAgent:
		"Finish setup before assigning this provider to an agent.",
	linkedAgents: "Linked agents",
	manageCustomBotsAndDiscoverClawdiBotsForYour:
		"Manage custom bots and discover Clawdi bots for your agents.",
	customBots: "Custom bots",
	clawdiBots: "Clawdi bots",
	linkAnAgentAndPairAChatWithoutLeaving: "Link an agent and pair a chat without leaving this page.",
	performance: "Performance",
	providerUnavailable: "Provider unavailable",
	runTheseCommandsInOrderOnTheMachine: "Run these commands in order on the machine",
	pasteThisPromptIntoClaudeCodeCodexHermesOpenClaw:
		"Paste this prompt into Claude Code, Codex, Hermes, OpenClaw, Pi, or OpenCode on the machine.",
	agentRegistered: "Agent registered",
	watchForYourAgent: "Watch for your agent",
	openAgent: "Open agent",
	thisAgentManagesItsFilesLocallyRunTheCommand:
		"This agent manages its files locally. Run the command on its host; skills appear here after the next sync.",
	syncedFromAgent: "Synced from agent",
	runThisCommandOnTheAgentMachineTheSkill:
		"Run this command on the agent machine. The skill belongs to that workspace.",
	noSetupRequired: "No setup required",
	walletBilled: "Wallet billed",
} as const;

export const agentDisconnectConfirmationCopy = {
	title: "Disconnect this agent?",
	beforeCommand: "Disconnect stops this installation and removes it from active views. Run ",
	command: "clawdi setup",
	afterCommand: " on it to reconnect with the same retained data.",
} as const;
