export const agentSurfaceCopy = {
	aIProviders: "AI Providers",
	aIProviders2: "AI providers",
	activity: "Activity",
	addACustomTelegramDiscordOrWhatsapp:
		"Add a Custom Telegram, Discord, or WhatsApp account you manage.",
	agentSoftware: "Agent software",
	agents: "Agents",
	askYourAgentToSetUpClawdi: "Ask your agent to set up Clawdi",
	avatar: "Avatar",
	channels: "Channels",
	clawdi: "Clawdi",
	commands: "Commands",
	compute: "Compute",
	connectAProviderToUseYourOwn: "Connect a provider to use your own model access with agents.",
	connectAnAgentToSeeItHere: "Connect an Agent to see it here.",
	couldnTLoadClawdiBots: "Couldn't load Clawdi bots",
	couldnTLoadAgent: "Couldn't load agent",
	couldnTLoadAgents: "Couldn't load agents",
	couldnTLoadChannelHealth: "Couldn't load channel health",
	couldnTLoadChannels: "Couldn't load channels",
	couldnTLoadSyncedSkills: "Couldn't load synced Skills",
	couldnTLoadProviders: "Couldn\u2019t load providers",
	default: "Default",
	deployAnAgent: "Deploy an Agent",
	deployFirstThenConfigureModelAccessInside:
		"Deploy first, then configure model access inside the Agent.",
	disconnect: "Disconnect",
	everyAgentInYourAccount: "Every Agent in your account.",
	gitHubSkillRepository: "GitHub Skill repository",
	health: "Health",
	imageUpTo2Mb: "Image up to 2 MB.",
	installOnTheAgent: "Install on the Agent",
	installSkill: "Install skill",
	name: "Name",
	noAgentsYet: "No Agents yet",
	noSkillsHaveSyncedFromThisAgent:
		"No Skills have synced from this Agent yet. Install one with the CLI, then sync the Agent.",
	noBotsYet: "No bots yet",
	noPluginsFound: "No plugins found",
	noProvidersAdded: "No providers added",
	noSetupRequiredUsageDrawsFromYour: "No setup required. Usage draws from your Wallet.",
	nodeJs24IsRequired: "Node.js 24+ is required.",
	personalize: "Personalize",
	plugins: "Plugins",
	recommended: "Recommended",
	searchPlugins: "Search plugins\u2026",
	setupPrompt: "Setup prompt",
	shownInTheSidebarPickersAndAgent: "Shown in the sidebar, pickers, and agent lists.",
	status: "Status",
	stopThisInstallationWhileKeepingItsClawdi:
		"Stop this installation while keeping its Clawdi data.",
	tryADifferentSearchOrCategory: "Try a different search or category.",
	uninstallSkill: "Uninstall skill",
	useAShortNameThatDistinguishesThis: "Use a short name that distinguishes this agent from others.",
	ownerRepoOrOwnerRepoPathTo: "owner/repo or owner/repo/path-to-skill\u2026",
	readOnly: "Read-only",
	unavailable: "Unavailable",
	couldnTUpdatePlugin: "Couldn't update plugin",
	installed: "Installed",
	available: "Available",
	thisPluginIsNoLongerAvailableInTheStore: "This plugin is no longer available in the Store.",
	customUpload: "Custom upload",
	syncStopsAndRetainedSessionsSkillsFilesAndProjects:
		"Sync stops and retained Sessions, Skills, files, and Projects stay in your account.",
	disconnectAgent: "Disconnect agent",
	chooseHowYourAgentsReachAModel: "Choose how your agents reach a model.",
	yourProviders: "Your providers",
	addACredentialBeforeAssigningThisProviderToAn:
		"Add a credential before assigning this provider to an agent.",
	finishSetupBeforeAssigningThisProviderToAnAgent:
		"Finish setup before assigning this provider to an agent.",
	linkedAgents: "Linked Agents",
	manageCustomBotsAndDiscoverClawdiBotsForYour:
		"Manage Custom bots and discover Clawdi bots for your Agents.",
	customBots: "Custom bots",
	clawdiBots: "Clawdi bots",
	linkAnAgentAndPairAChatWithoutLeaving: "Link an Agent and pair a chat without leaving this page.",
	performance: "Performance",
	providerUnavailable: "Provider unavailable",
	runTheseCommandsInOrderOnTheMachine: "Run these commands in order on the machine",
	preferBunUseBunAddGClawdiLatest: "Prefer Bun? Use: bun add -g clawdi@latest",
	pasteThisPromptIntoClaudeCodeCodexHermesOpenClaw:
		"Paste this prompt into Claude Code, Codex, Hermes, OpenClaw, Pi, or OpenCode on the machine.",
	agentRegistered: "Agent registered",
	watchForYourAgent: "Watch for your agent",
	openAgent: "Open agent",
	thisAgentManagesItsFilesLocallyRunTheCommand:
		"This Agent manages its files locally. Run the command on its host; Skills appear here after the next sync.",
	syncedFromAgent: "Synced from Agent",
	runThisCommandOnTheAgentMachineTheSkill:
		"Run this command on the Agent machine. The Skill belongs to that Workspace.",
	noSetupRequired: "No setup required",
	walletBilled: "Wallet billed",
} as const;

export const agentDisconnectConfirmationCopy = {
	title: "Disconnect this agent?",
	beforeCommand: "Disconnect stops this installation and removes it from active views. Run ",
	command: "clawdi setup",
	afterCommand: " on it to reconnect with the same retained data.",
} as const;
