/** Product copy from Web settings, reused by the native translation catalog. */
export const settingsCopy = {
	keyNameHelp: "For example, the server, container, or automation that will use this key.",
	general: "General",
	generalDescription: "Account and app preferences.",
	account: "Account",
	accountDescription: "Your Clawdi identity.",
	manageAccount: "Manage account",
	appearance: "Appearance",
	theme: "Theme",
	themeDescription: "Light, dark, or match your system.",
	light: "Light",
	dark: "Dark",
	system: "System",
	apiKeys: "API Keys",
	apiKeysDescription:
		"Manage bearer tokens for servers, containers, and other headless environments.",
	createKey: "Create API key",
	laptopTitle: "Using Clawdi on a laptop?",
	laptopBefore: "Run ",
	laptopCommand: "clawdi auth login",
	laptopAfter: " instead; it completes sign-in without a manually managed key.",
	created: "Created",
	lastUsed: "Last used",
	expires: "Expires",
	never: "Never",
	revoke: "Revoke",
	revokeTitle: "Revoke “{label}”?",
	revokeKey: "Revoke key",
	emptyKeys: "No active API keys",
	emptyKeysDescription:
		"Create a key to authenticate a server, container, or other client that can’t open a browser.",
	keyName: "Key name",
	keyPlaceholder: "Production server",
	createDescription: "Use a recognizable name so you know which client can be revoked later.",
	saveKey: "Save your API key",
	saveKeyDescription: "Copy this key now. For your security, it won’t be available again.",
	keyCreated: "Key created",
	storeKey: "Store it in your secret manager and set it as CLAWDI_AUTH_TOKEN on the client.",
	done: "Done",
	acknowledgeKey: "I have copied and stored this API key safely.",
	revokeDescription:
		"Requests using this key will stop working. This can’t be undone; create and install a new key to reconnect the client.",
} as const;
export const billingCopy = {
	usedBy: "Used by",
	edit: "Edit",
	comingSoon: "Coming soon",
	autoReloadCardHint: "Auto-reload uses the card selected in Auto-reload below.",
	autoReloadThreshold: "When balance is below (USD)",
	autoReloadAmount: "Amount to add (USD)",
	autoReloadMonthlyLimit: "Monthly limit (USD)",
	sharedPricingUnavailable:
		"A shared Basic and Performance billing term is not currently available.",
	lowBalance: "Low — top up before Clawdi AI pauses",
	topUp: "Top up",
	plans: "Plans",
	plansDescription: "Compare hosted compute plans.",
	basic: "Compute Basic",
	performance: "Compute Performance",
	basicDescription: "Balanced capacity for everyday workloads.",
	performanceDescription: "Higher capacity for production workloads.",
	basicSubscription: "Basic subscription",
	performanceSubscription: "Performance subscription",
	pricingUnavailable: "Pricing unavailable",
	confidentialCompute: "Managed confidential compute · choose OpenClaw or Hermes",
	byok: "Bring your own API key (BYOK) · pay your provider directly",
	upTo: "Up to",
	storage: "storage",
	paymentMethods: "Payment methods",
	paymentMethodsDescription: "Cards saved to your billing account.",
	autoReload: "Auto-reload",
	autoReloadDescription: "Automatically add funds when your balance is low.",
	usdc: "USDC from a browser wallet",
	usdcUnavailable: "Browser-wallet USDC funding is not available for this account yet.",

	compute: "Compute",
	computeDescription: "Subscriptions, plans, and account billing for hosted agents.",
	subscriptions: "Your subscriptions",
	subscriptionsDescription: "Manage every compute subscription in one place.",
	emptySubscriptions: "No compute subscriptions",
	emptySubscriptionsDescription:
		"Compute subscriptions will appear here when you start a hosted agent.",
	wallet: "Wallet",
	walletDescription: "Add funds and manage how your Clawdi usage is paid.",
	walletBalance: "Wallet balance",
	walletExplanation:
		"Pays for AI usage and wallet-funded compute subscriptions. Card-paid subscriptions do not use this balance.",
	transactions: "Transactions",
	transactionsDescription: "Top-ups, compute payments, credits, and adjustments.",
	transactionsCount: "Showing {count} transactions",
	emptyTransactions: "No transactions yet",
	emptyTransactionsDescription:
		"Top-ups, grants, compute charges, and other money movements will appear here.",
} as const;
