"""Generic Clawdi mitmproxy profile interpreter.

The addon intentionally contains no product hostnames or route constants. It
reads all routing policy from a clawdi.mitmProfiles.v1 bundle and a sidecar-only
secret JSON file generated by the CLI at runtime.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, quote, unquote, urlsplit

try:  # pragma: no cover - exercised only under mitmdump.
    from mitmproxy import ctx, http
except Exception:  # pragma: no cover - used by unit tests without mitmproxy.

    class _FallbackLog:
        def info(self, message: str) -> None:
            return None

        def warn(self, message: str) -> None:
            return None

        def error(self, message: str) -> None:
            return None

    class _FallbackCtx:
        log = _FallbackLog()

    class _FallbackResponse:
        @staticmethod
        def make(status_code: int, content: bytes, headers: dict[str, str]) -> dict[str, Any]:
            return {"status_code": status_code, "content": content, "headers": headers}

    class _FallbackHttp:
        Response = _FallbackResponse

    ctx = _FallbackCtx()
    http = _FallbackHttp()


SCHEMA_VERSION = "clawdi.mitmProfiles.v1"
ENV_FILE_KEY = "CLAWDI_MITM_ENV_FILE"


@dataclass(frozen=True)
class ProfileDecision:
    action: str
    profile_id: str | None = None
    reason: str | None = None


class ConfigError(RuntimeError):
    pass


class ClawdiMitmAddon:
    def __init__(self) -> None:
        self.profile_bundle_path: Path | None = None
        self.secret_file_path: Path | None = None
        self.profiles: list[dict[str, Any]] = []
        self.secrets: dict[str, str] = {}
        self.profile_hosts: set[str] = set()

    def load(self, loader: Any) -> None:  # pragma: no cover - mitmproxy integration glue.
        self.reload_from_environment(os.environ)

    def requestheaders(self, flow: Any) -> None:  # pragma: no cover - behavior covered via request.
        flow.request.stream = True

    def responseheaders(self, flow: Any) -> None:  # pragma: no cover - behavior covered via request.
        flow.response.stream = True

    def tls_clienthello(self, data: Any) -> None:
        server_name = normalize_host(getattr(data.client_hello, "sni", "") or "")
        if not server_name or not self.should_intercept_sni(server_name):
            data.ignore_connection = True

    def request(self, flow: Any) -> None:
        decision = self.apply_to_flow(flow)
        if decision.profile_id:
            ctx.log.info(
                f"clawdi mitm action={decision.action} profile={decision.profile_id} "
                f"url={redact_url(flow.request.url, matched_profile(flow, self.profiles))}"
            )

    def reload_from_environment(self, environ: dict[str, str | None]) -> None:
        config = merged_config(environ)
        bundle = first_nonempty(
            config.get("CLAWDI_MITM_PROFILE_BUNDLE"),
            config.get("CLAWDI_MITM_PROFILE_BUNDLE_PATH"),
        )
        if not bundle:
            raise ConfigError("CLAWDI_MITM_PROFILE_BUNDLE is required")
        secret_file = first_nonempty(
            config.get("CLAWDI_MITM_SECRET_FILE"),
            config.get("CLAWDI_MITM_SECRETS_FILE"),
        )
        self.profile_bundle_path = Path(bundle)
        self.secret_file_path = Path(secret_file) if secret_file else None
        self.profiles = load_profiles(self.profile_bundle_path)
        self.secrets = load_secrets(self.secret_file_path)
        self.profile_hosts = profile_host_set(self.profiles)

    def should_intercept_sni(self, server_name: str) -> bool:
        return normalize_host(server_name) in self.profile_hosts

    def apply_to_flow(self, flow: Any) -> ProfileDecision:
        profile = first_matching_profile(flow, self.profiles, self.secrets)
        if profile is None:
            return ProfileDecision("allow")
        kind = profile.get("kind")
        if kind == "deny":
            flow.response = http.Response.make(
                403,
                b"Request blocked by managed egress policy.\n",
                {"content-type": "text/plain; charset=utf-8"},
            )
            return ProfileDecision("deny", str(profile.get("id")))
        if kind == "passthrough":
            return ProfileDecision("passthrough", str(profile.get("id")))
        if kind == "provider":
            apply_rewrite_headers(flow, profile, self.secrets)
            return ProfileDecision("provider", str(profile.get("id")))
        if kind in {"http", "websocket"}:
            apply_http_rewrite(flow, profile, self.secrets)
            return ProfileDecision(kind, str(profile.get("id")))
        return ProfileDecision("allow", str(profile.get("id")), "unknown-kind")


def merged_config(environ: dict[str, str | None]) -> dict[str, str]:
    config: dict[str, str] = {}
    env_file = first_nonempty(environ.get(ENV_FILE_KEY))
    if env_file:
        config.update(parse_env_file(Path(env_file)))
    for key, value in environ.items():
        if value is not None and key.startswith("CLAWDI_"):
            config[key] = value
    return config


def parse_env_file(path: Path) -> dict[str, str]:
    config: dict[str, str] = {}
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError as exc:
        raise ConfigError(f"MITM env file is missing: {path}") from exc
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
            continue
        config[key] = unquote_env_value(value.strip())
    return config


def unquote_env_value(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1]
    return value.replace(r"\"", '"').replace(r"\n", "\n")


def load_profiles(path: Path) -> list[dict[str, Any]]:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ConfigError(f"MITM profile bundle is missing: {path}") from exc
    if raw.get("schemaVersion") != SCHEMA_VERSION:
        raise ConfigError(f"MITM profile bundle must use {SCHEMA_VERSION}")
    profiles = raw.get("profiles")
    if not isinstance(profiles, list):
        raise ConfigError("MITM profile bundle profiles must be an array")
    return sorted(
        [profile for profile in profiles if isinstance(profile, dict) and profile.get("enabled", True)],
        key=lambda profile: (int(profile.get("priority", 100)), str(profile.get("id", ""))),
    )


def load_secrets(path: Path | None) -> dict[str, str]:
    if path is None:
        return {}
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}
    if not isinstance(raw, dict):
        return {}
    return {str(key): str(value) for key, value in raw.items() if isinstance(value, str)}


def profile_host_set(profiles: list[dict[str, Any]]) -> set[str]:
    hosts: set[str] = set()
    for profile in profiles:
        match = profile.get("match")
        if isinstance(match, dict):
            host = normalize_host(str(match.get("host", "")))
            if host:
                hosts.add(host)
    return hosts


def first_matching_profile(
    flow: Any,
    profiles: list[dict[str, Any]],
    secrets: dict[str, str],
) -> dict[str, Any] | None:
    for profile in profiles:
        if profile_matches(flow, profile, secrets):
            return profile
    return None


def matched_profile(flow: Any, profiles: list[dict[str, Any]]) -> dict[str, Any] | None:
    for profile in profiles:
        if host_matches(flow, profile):
            return profile
    return None


def profile_matches(flow: Any, profile: dict[str, Any], secrets: dict[str, str]) -> bool:
    if not host_matches(flow, profile):
        return False
    match = profile.get("match")
    if not isinstance(match, dict):
        return False
    kind = profile.get("kind")
    request_scheme = request_profile_scheme(flow)
    configured_scheme = match.get("scheme")
    if configured_scheme and configured_scheme != request_scheme:
        return False
    if kind == "websocket" and not is_websocket_request(flow):
        return False
    if kind in {"http", "provider"} and is_websocket_request(flow):
        return False
    path = request_path_only(flow)
    path_prefix = match.get("pathPrefix")
    if isinstance(path_prefix, str) and not path.startswith(path_prefix):
        return False
    path_match = match.get("path")
    if isinstance(path_match, dict) and not path_matcher_matches(path, path_match, secrets):
        return False
    headers = match.get("headers")
    if isinstance(headers, dict):
        for name, matcher in headers.items():
            if not matcher_matches(
                header_get_optional(flow.request.headers, str(name)),
                matcher,
                secrets,
            ):
                return False
    query = match.get("query")
    if isinstance(query, dict):
        query_values = parse_qs(urlsplit(getattr(flow.request, "path", "")).query)
        for name, matcher in query.items():
            value = first_query_value(query_values, str(name))
            if not matcher_matches(value, matcher, secrets):
                return False
    return True


def host_matches(flow: Any, profile: dict[str, Any]) -> bool:
    match = profile.get("match")
    if not isinstance(match, dict):
        return False
    expected = normalize_host(str(match.get("host", "")))
    if not expected:
        return False
    return expected in request_host_candidates(flow)


def request_host_candidates(flow: Any) -> set[str]:
    candidates: set[str] = set()
    for value in (
        getattr(flow.request, "pretty_host", None),
        getattr(flow.request, "host", None),
        header_get(flow.request.headers, "host"),
    ):
        host = normalize_host(str(value or ""))
        if host:
            candidates.add(host)
    return candidates


def normalize_host(value: str) -> str:
    host = value.strip().lower()
    if not host:
        return ""
    if host.startswith("[") and "]" in host:
        return host[1 : host.index("]")]
    if ":" in host and host.count(":") == 1:
        return host.split(":", 1)[0]
    return host.strip(".")


def request_profile_scheme(flow: Any) -> str:
    scheme = str(getattr(flow.request, "scheme", "") or "").lower()
    if is_websocket_request(flow):
        return "wss" if scheme == "https" else "ws"
    return scheme


def is_websocket_request(flow: Any) -> bool:
    return header_get(flow.request.headers, "upgrade").lower() == "websocket"


def request_path_only(flow: Any) -> str:
    path = getattr(flow.request, "path", "") or "/"
    split = urlsplit(path)
    return split.path or "/"


def first_query_value(values: dict[str, list[str]], name: str) -> str | None:
    found = values.get(name)
    if not found:
        return None
    return found[0]


def path_matcher_matches(path: str, matcher: dict[str, Any], secrets: dict[str, str]) -> bool:
    matcher_type = matcher.get("type")
    if matcher_type == "equals":
        return path == matcher.get("value")
    if matcher_type == "prefix":
        return path.startswith(str(matcher.get("value", "")))
    if matcher_type in {"secretRefEquals", "secretRefPrefix"}:
        secret = secrets.get(str(matcher.get("secretRef", "")))
        if secret is None:
            return False
        expected = f"{matcher.get('prefix', '')}{secret}{matcher.get('suffix', '')}"
        if matcher_type == "secretRefEquals":
            return path == expected
        return path.startswith(expected)
    return False


def matcher_matches(value: str | None, matcher: Any, secrets: dict[str, str]) -> bool:
    if not isinstance(matcher, dict):
        return False
    matcher_type = matcher.get("type")
    if matcher_type == "exists":
        return value is not None
    if value is None:
        return False
    if matcher_type == "equals":
        return value == f"{matcher.get('prefix', '')}{matcher.get('value', '')}"
    if matcher_type == "secretRefEquals":
        secret = secrets.get(str(matcher.get("secretRef", "")))
        return secret is not None and value == f"{matcher.get('prefix', '')}{secret}"
    return False


def apply_rewrite_headers(flow: Any, profile: dict[str, Any], secrets: dict[str, str]) -> None:
    rewrite = profile.get("rewrite") if isinstance(profile.get("rewrite"), dict) else {}
    for name, setter in rewrite.get("setHeaders", {}).items():
        resolved = resolve_header_setter(setter, secrets)
        if resolved is not None:
            header_set(flow.request.headers, str(name), resolved)


def apply_http_rewrite(flow: Any, profile: dict[str, Any], secrets: dict[str, str]) -> None:
    rewrite = profile.get("rewrite") if isinstance(profile.get("rewrite"), dict) else {}
    upstream = str(rewrite.get("upstreamBaseUrl", ""))
    parsed = urlsplit(upstream)
    if not parsed.scheme or not parsed.hostname:
        return
    original_path = getattr(flow.request, "path", "") or "/"
    original_path = apply_path_replace(original_path, rewrite, secrets)
    target_scheme = "https" if parsed.scheme == "wss" else "http" if parsed.scheme == "ws" else parsed.scheme
    flow.request.scheme = target_scheme
    flow.request.host = parsed.hostname
    flow.request.port = parsed.port or default_port(parsed.scheme)
    header_set(flow.request.headers, "host", parsed.netloc)
    preserve_path = bool(rewrite.get("preservePath", True))
    flow.request.path = combine_paths(parsed.path or "/", original_path if preserve_path else "")
    apply_rewrite_headers(flow, profile, secrets)


def apply_path_replace(request_path: str, rewrite: dict[str, Any], secrets: dict[str, str]) -> str:
    replacement = rewrite.get("pathReplace")
    if not isinstance(replacement, dict):
        return request_path
    if replacement.get("type") != "secretRefPrefix":
        return request_path
    placeholder = secrets.get(str(replacement.get("secretRef", "")))
    actual = secrets.get(str(replacement.get("replacementSecretRef", "")))
    if placeholder is None or actual is None:
        return request_path
    split = urlsplit(request_path or "/")
    prefix = str(replacement.get("prefix", ""))
    suffix = str(replacement.get("suffix", ""))
    expected = f"{prefix}{placeholder}{suffix}"
    if not split.path.startswith(expected):
        return request_path
    replaced_path = f"{prefix}{actual}{suffix}{split.path[len(expected):]}"
    return f"{replaced_path}?{split.query}" if split.query else replaced_path


def combine_paths(base_path: str, original_path: str) -> str:
    original = urlsplit(original_path or "/")
    if not original_path:
        path = base_path or "/"
        query = ""
    else:
        left = "/" if base_path == "/" else base_path.rstrip("/")
        right = original.path if original.path.startswith("/") else f"/{original.path}"
        path = f"{left}{right}" if left != "/" else right
        query = original.query
    return f"{path}?{query}" if query else path


def default_port(scheme: str) -> int:
    return 443 if scheme in {"https", "wss"} else 80


def resolve_header_setter(setter: Any, secrets: dict[str, str]) -> str | None:
    if isinstance(setter, str):
        return setter
    if isinstance(setter, dict) and setter.get("type") == "secretRef":
        secret = secrets.get(str(setter.get("secretRef", "")))
        if secret is None:
            return None
        return f"{setter.get('prefix', '')}{secret}"
    return None


def header_get(headers: Any, name: str) -> str:
    return header_get_optional(headers, name) or ""


def header_get_optional(headers: Any, name: str) -> str | None:
    if headers is None:
        return None
    try:
        value = headers.get(name, None)
    except AttributeError:
        value = None
    if value is not None:
        return str(value)
    lower = name.lower()
    for key, item in getattr(headers, "items", lambda: [])():
        if str(key).lower() == lower:
            return str(item)
    return None


def header_set(headers: Any, name: str, value: str) -> None:
    headers[name] = value


def redact_url(url: str, profile: dict[str, Any] | None) -> str:
    redacted = url
    if not profile:
        return redacted
    logging_config = profile.get("logging")
    if not isinstance(logging_config, dict):
        return redacted
    for pattern in logging_config.get("redactUrlPatterns", []):
        try:
            redacted = re.sub(str(pattern), "[redacted]", redacted)
        except re.error:
            continue
    return redacted


def redacted_headers(headers: Any, profile: dict[str, Any] | None) -> dict[str, str]:
    logging_config = profile.get("logging") if isinstance(profile, dict) else {}
    redact = {
        str(name).lower()
        for name in logging_config.get("redactHeaders", [])
        if isinstance(logging_config, dict)
    }
    output: dict[str, str] = {}
    for key, value in getattr(headers, "items", lambda: [])():
        output[str(key)] = "[redacted]" if str(key).lower() in redact else str(value)
    return output


def first_nonempty(*values: str | None) -> str | None:
    for value in values:
        if value and value.strip():
            return value.strip()
    return None


addons = [ClawdiMitmAddon()]
