export const addKeysDialogClasses = {
	iconSmall: "size-3.5",
	dialog: "sm:max-w-lg",
	mono: "font-mono",
	body: "space-y-3",
	paste: "resize-none font-mono text-xs",
	destinationGrid: "grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end",
	field: "space-y-1.5",
	trigger: "w-full",
	emoji: "select-none",
	newField: "space-y-1",
	newInput: "sm:w-44",
	error: "max-w-44 text-xs text-destructive",
	icon: "size-4",
	errors: "max-h-32 list-disc space-y-1 overflow-auto pl-4",
	conflicts: "flex items-start gap-3 rounded-md border bg-muted/30 p-3",
	checkbox: "mt-0.5",
	label: "text-sm font-medium",
	meta: "text-xs text-muted-foreground",
	preview: "rounded-md border",
	previewHeader: "flex items-center justify-between gap-2 border-b px-3 py-2",
	previewTitle: "text-xs font-medium",
	badges: "flex flex-wrap gap-1.5",
	previewList: "max-h-44 divide-y overflow-auto",
	previewRow: "grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 px-3 py-2 text-sm",
	key: "truncate font-mono text-xs",
	more: "px-3 py-2 text-xs text-muted-foreground",
	footer: "flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between",
	count: "text-xs text-muted-foreground tabular-nums",
	footerActions: "sm:ml-auto",
} as const;
