/** Verbatim Web recipes; native adds only layout structure. */
export const apiKeysPanelClasses = {
	panel: "flex flex-col gap-8 px-5 sm:px-6 lg:px-8",
	notice: "flex items-start gap-3 rounded-lg border bg-muted/20 px-4 py-3 text-sm",
	noticeIcon: "mt-0.5 size-4 shrink-0 text-muted-foreground",
	muted: "text-muted-foreground",
	strong: "font-medium text-foreground",
	command: "rounded bg-muted px-1 py-0.5 font-mono text-xs",
	desktopOnly: "hidden md:block",
	mobileOnly: "md:hidden",
	dialog: "sm:max-w-lg",
	form: "space-y-5",
	createdAlert: "border-primary/30 bg-primary/5",
	mono: "font-mono text-xs",
	secretBox: "flex min-w-0 items-start gap-2 rounded-lg border bg-muted/30 p-2",
	secret: "min-w-0 flex-1 select-all break-all px-1 py-1.5 font-mono text-xs leading-relaxed",
	acknowledgement: "flex items-start gap-2.5",
	checkbox: "mt-0.5",
	acknowledgementLabel: "text-sm leading-snug font-normal",
	field: "space-y-2",
	description: "text-xs text-muted-foreground",
	error: "text-xs text-destructive",
	keyName: "block min-w-0 truncate font-medium",
	keyPrefix: "block min-w-0 truncate font-mono text-xs text-muted-foreground",
	revoke: "text-muted-foreground hover:text-destructive",
	emptyContainer: "rounded-lg border bg-card",
	emptyPadding: "p-8 sm:p-12",
	mobileSkeletons: "flex flex-col gap-3 md:hidden",
	screenReader: "sr-only",
	skeletonCard: "rounded-lg border bg-card p-4",
	skeletonName: "h-4 w-2/3",
	skeletonPrefix: "mt-3 h-3 w-1/2",
	skeletonAction: "mt-4 h-8 w-full",
	cards: "flex flex-col gap-3",
	card: "min-w-0 rounded-lg border bg-card p-4",
	cardHeader: "grid min-w-0 grid-cols-[minmax(0,1fr)_auto] items-start gap-3",
	factBody: "min-w-0",
	cardName: "line-clamp-2 break-all text-sm font-medium",
	cardPrefix: "mt-1.5 max-w-full",
	facts: "mt-4 grid grid-cols-2 gap-x-4 gap-y-3 border-t pt-3 text-xs",
	factValue: "mt-0.5 font-medium text-foreground",
} as const;
