export const channelDetailPageClasses = {
	infoTint: "bg-primary/10 text-primary",
	agentIdentity: "min-w-0 flex-1",
	notice: "rounded-lg border bg-card p-4",
	noticeHeader: "flex items-start gap-3",
	noticeIcon: "size-9 [&>svg]:size-5",
	noticeBody: "min-w-0 flex-1 space-y-1",
	noticeTitle: "text-sm font-medium",
	noticeDescription: "text-sm text-muted-foreground",
	sectionHeader: "flex flex-wrap items-center justify-between gap-2",
	sectionAction: "shrink-0",
	skeletonContent: "flex flex-col gap-4",
	titleSkeleton: "h-9 w-full max-w-xl rounded-lg",
	contentSkeleton: "h-64 w-full rounded-lg",
	statusMeta: "flex flex-wrap items-center gap-2 text-sm text-muted-foreground",
	removeAction: "text-muted-foreground hover:text-destructive",
	actionIcon: "size-4",
	linkedAgents: "flex flex-col gap-3",
	tabs: "min-w-0",
	tabsList: "h-auto flex-wrap justify-start",
	agentsSkeleton: "h-24 w-full rounded-lg",
	agentActions: "flex shrink-0 items-center gap-1.5",
	agentActionIcon: "size-3.5",
	activitySkeleton: "h-32 w-full rounded-lg",
	activityList: "flex flex-col gap-2",
	activityHeading: "flex flex-wrap items-center gap-2",
	activityType: "text-xs font-medium capitalize",
	activityTime: "shrink-0 text-xs text-muted-foreground sm:ml-auto",
	activityText: "mt-1 text-sm",
	activityError: "mt-1 flex items-start gap-1 text-xs text-destructive",
	activityErrorIcon: "mt-0.5 size-3 shrink-0",
	externalChat: "mt-1",
	healthError: "flex flex-col gap-1 border-destructive/30 bg-destructive/5",
	healthMeta: "text-xs text-muted-foreground",
	healthStats: "grid grid-cols-2 gap-2 sm:grid-cols-4",
	healthStatValue: "text-2xl font-semibold tabular-nums",
	errorTitle: "flex items-center gap-1.5 text-sm font-medium text-destructive",
	errorDescription: "text-sm text-destructive/90",
	transportHeading: "mb-3 px-0",
	transportStats: "grid gap-3 text-sm sm:grid-cols-3",
	transportValue: "mt-0.5 font-medium",
	commandsHeading: "text-xs font-medium text-success-muted-foreground",
	command: "flex items-baseline gap-2 text-sm",
	commandName: "font-mono text-xs",
	commandDescription: "text-muted-foreground",
} as const;
