export const channelDetailPageClasses = {
	minWFlex: "min-w-0 flex-1",
	roundedLgBorderBgCardP: "rounded-lg border bg-card p-4",
	flexItemsStartGap: "flex items-start gap-3",
	sizeSvgSize: "size-9 [&>svg]:size-5",
	minWFlexSpaceY: "min-w-0 flex-1 space-y-1",
	textSmFontMedium: "text-sm font-medium",
	textSmTextMutedForeground: "text-sm text-muted-foreground",
	flexFlexWrapItemsCenterJustifyBetween: "flex flex-wrap items-center justify-between gap-2",
	shrink: "shrink-0",
	flexFlexColGap: "flex flex-col gap-4",
	hWFullMaxWXlRoundedLg: "h-9 w-full max-w-xl rounded-lg",
	hWFullRoundedLg: "h-64 w-full rounded-lg",
	flexFlexWrapItemsCenterGap: "flex flex-wrap items-center gap-2 text-sm text-muted-foreground",
	textMutedForegroundHoverTextDestructive: "text-muted-foreground hover:text-destructive",
	size: "size-4",
	flexFlexColGap2: "flex flex-col gap-3",
	minW: "min-w-0",
	hAutoFlexWrapJustifyStart: "h-auto flex-wrap justify-start",
	hWFullRoundedLg2: "h-24 w-full rounded-lg",
	flexShrinkItemsCenterGap: "flex shrink-0 items-center gap-1.5",
	size2: "size-3.5",
	hWFullRoundedLg3: "h-32 w-full rounded-lg",
	flexFlexColGap3: "flex flex-col gap-2",
	flexFlexWrapItemsCenterGap2: "flex flex-wrap items-center gap-2",
	textXsFontMediumCapitalize: "text-xs font-medium capitalize",
	shrinkTextXsTextMutedForegroundSmMlAuto: "shrink-0 text-xs text-muted-foreground sm:ml-auto",
	mtTextSm: "mt-1 text-sm",
	mtFlexItemsStartGap: "mt-1 flex items-start gap-1 text-xs text-destructive",
	mtSizeShrink: "mt-0.5 size-3 shrink-0",
	mt: "mt-1",
	textXsTextMutedForeground: "text-xs text-muted-foreground",
	gridGridColsGapSmGridCols: "grid grid-cols-2 gap-2 sm:grid-cols-4",
	textXlFontSemiboldTabularNums: "text-2xl font-semibold tabular-nums",
	flexItemsCenterGapTextSm: "flex items-center gap-1.5 text-sm font-medium text-destructive",
	textSmTextDestructive: "text-sm text-destructive/90",
	mbPx: "mb-3 px-0",
	gridGapTextSmSmGridCols: "grid gap-3 text-sm sm:grid-cols-3",
	mtFontMedium: "mt-0.5 font-medium",
	textXsFontMediumTextSuccessMutedForeground: "text-xs font-medium text-success-muted-foreground",
	flexItemsBaselineGapTextSm: "flex items-baseline gap-2 text-sm",
	fontMonoTextXs: "font-mono text-xs",
	textMutedForeground: "text-muted-foreground",
} as const;
