/** Exact Web recipes from apps/web/src/components/dashboard/connected-agent-detail.tsx. */
export const connectedAgentDetailClasses = {
	statusTint: "bg-identity-7-bg text-identity-7-fg",
	section: "flex flex-col gap-6",
	sectionIcon: "size-4 text-muted-foreground",
	overview: "flex flex-col gap-8",
	sectionTitle: "text-sm font-semibold",
	viewAll: "text-muted-foreground",
	sessions: "min-w-0",
	statusLabel: "flex items-center gap-2",
	statusContent: "flex h-full flex-col justify-end",
	sectionSkeleton: "flex min-h-0 w-full flex-1 flex-col overflow-hidden",
	sectionSkeletonBody: "flex min-h-0 flex-1 flex-col overflow-hidden bg-background",
	sectionSkeletonHeader: "flex h-12 shrink-0 items-center justify-between gap-3 px-4 lg:px-6",
	sectionSkeletonHeading: "flex min-w-0 items-center gap-2",
	sectionIconSkeleton: "size-4 shrink-0 rounded-sm",
	sectionTitleSkeleton: "h-4 w-32 max-w-[45vw]",
	sectionActionSkeleton: "h-8 w-20 shrink-0",
	sectionContentSkeleton: "min-h-0 flex-1 rounded-none",
	skeletonContent: "space-y-4",
	metadataSkeleton: "h-4 w-28",
	descriptionSkeleton: "h-4 w-56 max-w-full",
	contentSkeleton: "h-40 w-full",
	activityTitleSkeleton: "h-lh w-28",
	activityActionSkeleton: "h-8 w-20",
	machineSkeleton: "h-lh w-24",
	lastSeenSkeleton: "h-lh w-20",
} as const;
