/** Exact Web recipes from apps/web/src/components/dashboard/connected-agent-detail.tsx. */
export const connectedAgentDetailClasses = {
	statusTint: "bg-identity-7-bg text-identity-7-fg",
	flexFlexColGap: "flex flex-col gap-6",
	sizeTextMutedForeground: "size-4 text-muted-foreground",
	flexFlexColGap2: "flex flex-col gap-8",
	textSmFontSemibold: "text-sm font-semibold",
	textMutedForeground: "text-muted-foreground",
	minW: "min-w-0",
	flexItemsCenterGap: "flex items-center gap-2",
	flexHFullFlex: "flex h-full flex-col justify-end",
	flexMinHW: "flex min-h-0 w-full flex-1 flex-col overflow-hidden",
	flexMinHFlex: "flex min-h-0 flex-1 flex-col overflow-hidden bg-background",
	flexHShrinkItems: "flex h-12 shrink-0 items-center justify-between gap-3 px-4 lg:px-6",
	flexMinWItems: "flex min-w-0 items-center gap-2",
	sizeShrinkRoundedSm: "size-4 shrink-0 rounded-sm",
	hWMaxW: "h-4 w-32 max-w-[45vw]",
	hWShrink: "h-8 w-20 shrink-0",
	minHFlexRounded: "min-h-0 flex-1 rounded-none",
	spaceY: "space-y-4",
	hW: "h-4 w-28",
	hWMaxW2: "h-4 w-56 max-w-full",
	hWFull: "h-40 w-full",
	hLhW: "h-lh w-28",
	hW2: "h-8 w-20",
	hLhW2: "h-lh w-24",
	hLhW3: "h-lh w-20",
} as const;
