/** Verbatim Web recipes, shared with the native phone layout. */
export const dashboardPageClasses = {
	root: "space-y-5 px-4 lg:px-6",
	grid: "grid gap-4 lg:grid-cols-3",
	agents: "min-w-0 lg:col-span-2 lg:row-start-1",
	activity: "min-w-0 space-y-2 lg:col-span-2 lg:row-start-2",
	sectionTitle: "text-base font-semibold",
	sidebar: "min-w-0 space-y-4 lg:col-start-3 lg:row-span-3 lg:row-start-1",
	recentSessions: "min-w-0 space-y-2 lg:col-span-2 lg:row-start-3",
	recentSessionsHeader: "flex items-end justify-between",
	viewAll: "text-muted-foreground",
	graphSkeleton: "w-full",
	graphSkeletonLayout: "flex gap-1.5",
	graphSkeletonWeekdays: "flex w-3 shrink-0 flex-col items-center gap-[3px]",
	graphSkeletonWeekday: "h-[11px] w-2 rounded-[3px]",
	graphSkeletonBody: "min-w-0 flex-1",
	graphSkeletonWeeks: "flex max-h-[95px] overflow-hidden gap-[3px]",
	graphSkeletonWeek: "flex flex-col gap-[3px]",
	graphSkeletonCell: "size-[11px] rounded-[3px]",
	graphSkeletonMutedCell: "opacity-50",
	graphSkeletonMonths: "mt-1 flex h-4 items-center gap-10",
	graphSkeletonMonth: "h-2.5 w-6",
	connectCard: "py-4",
	connectCardContent: "flex items-center justify-between gap-3 px-4",
	connectCardTitle: "min-w-0 text-sm font-medium",
	greeting: "text-2xl font-semibold tracking-tight",
	greetingSkeleton: "h-8 w-64 max-w-full",
} as const;
