/** Verbatim Web recipes, shared with the native phone layout. */
export const dashboardPageClasses = {
	spaceY5Px4: "space-y-5 px-4 lg:px-6",
	gridGap4LgGrid: "grid gap-4 lg:grid-cols-3",
	minW0LgCol: "min-w-0 lg:col-span-2 lg:row-start-1",
	minW0SpaceY: "min-w-0 space-y-2 lg:col-span-2 lg:row-start-2",
	textBaseFontSemibold: "text-base font-semibold",
	minW0SpaceY2: "min-w-0 space-y-4 lg:col-start-3 lg:row-span-3 lg:row-start-1",
	minW0SpaceY3: "min-w-0 space-y-2 lg:col-span-2 lg:row-start-3",
	flexItemsEndJustifyBetween: "flex items-end justify-between",
	textMutedForeground: "text-muted-foreground",
	wFull: "w-full",
	flexGap15: "flex gap-1.5",
	flexW3Shrink0: "flex w-3 shrink-0 flex-col items-center gap-[3px]",
	h11PxW2Rounded: "h-[11px] w-2 rounded-[3px]",
	minW0Flex1: "min-w-0 flex-1",
	flexMaxH95PxOverflow: "flex max-h-[95px] overflow-hidden gap-[3px]",
	flexFlexColGap3Px: "flex flex-col gap-[3px]",
	size11PxRounded3Px: "size-[11px] rounded-[3px]",
	opacity50: "opacity-50",
	mt1FlexH4: "mt-1 flex h-4 items-center gap-10",
	h25W6: "h-2.5 w-6",
	py4: "py-4",
	flexItemsCenterJustifyBetween: "flex items-center justify-between gap-3 px-4",
	minW0TextSm: "min-w-0 text-sm font-medium",
	text2XlFontSemiboldTracking: "text-2xl font-semibold tracking-tight",
	h8W64Max: "h-8 w-64 max-w-full",
} as const;
