export const deployWizardClasses = {
	planPrice: "flex min-w-0 flex-col items-end text-right tabular-nums",
	planPriceHeading: "flex items-baseline justify-end leading-5",
	planPriceValue: "whitespace-nowrap text-sm font-semibold text-foreground",
	planPriceMeta: "text-xs leading-4 font-normal text-muted-foreground",
	priceSegment: "whitespace-nowrap",
	specs: "text-xs",
	form: "flex flex-col gap-6",
	providerChoices: "flex flex-col gap-4",
	providerSkeleton: "h-[74px] w-full rounded-lg",
	providerError: "@2xl/main:col-span-2",
	compute: "flex min-w-0 flex-col gap-4",
	loadingPlans: "flex items-center gap-2 text-sm text-muted-foreground",
	actionIcon: "size-3.5",
	billingTerm: "flex max-w-xs flex-col gap-1.5",
	fieldLabel: "text-xs text-muted-foreground",
	computeChoice: "items-center p-3",
	paymentMethods: "flex flex-col gap-3",
	fieldTitle: "text-sm font-medium",
	error: "text-xs text-destructive",
	personalizeSection: "pb-32 @2xl/main:pb-24",
	personalize: "flex max-w-2xl flex-col gap-4",
	nameField: "flex w-full max-w-md flex-col gap-1.5",
	screenReaderOnly: "sr-only",
	localeFields: "flex flex-wrap items-start gap-4",
	languageField: "flex flex-col gap-1.5",
	timezoneField: "flex w-full max-w-sm min-w-0 flex-col gap-1.5",
	actionBar:
		"sticky bottom-0 z-10 -mx-4 border-t bg-background/90 px-4 pt-3 pb-[calc(--spacing(3)+env(safe-area-inset-bottom))] backdrop-blur lg:-mx-6 lg:px-6",
	hydrationError: "mb-3",
	actionBarContent:
		"flex flex-col gap-2 @2xl/main:flex-row @2xl/main:items-center @2xl/main:justify-between",
	configurationSummary: "min-w-0 truncate text-xs text-muted-foreground sm:text-sm",
	checkout:
		"flex w-full shrink-0 flex-col gap-2 @2xl/main:w-auto @2xl/main:flex-row @2xl/main:items-center @2xl/main:justify-end",
	amount: "flex min-w-0 flex-col @2xl/main:w-56 @2xl/main:items-end @2xl/main:text-right",
	amountHeading: "flex flex-wrap items-center gap-x-2 gap-y-0.5 @2xl/main:justify-end",
	amountValue: "font-semibold tabular-nums text-foreground",
	refreshQuote: "h-auto p-0",
	amountCaption: "whitespace-nowrap text-xs text-muted-foreground",
	amountError: "whitespace-nowrap text-xs font-medium text-destructive",
	submitGroup: "flex min-w-0 flex-col gap-1 @2xl/main:w-40 @2xl/main:items-end",
	submit: "w-full shrink-0",
} as const;
