export const initialDeploymentClasses = {
	panel: "p-6 md:p-8",
	warningPanel: "border-warning/30 bg-warning-muted",
	failurePanel: "border-destructive/30 bg-destructive-muted p-6 md:p-8",
	body: "space-y-6",
	failureBody: "space-y-5",
	title: "flex items-center gap-2 text-lg font-semibold",
	description: "mt-1 text-sm text-muted-foreground",
	stageHeader: "flex items-baseline justify-between gap-4",
	activeLabel: "inline-flex items-center gap-2 text-base font-semibold",
	step: "shrink-0 text-xs font-medium text-muted-foreground",
	stageDescription: "mt-2 text-sm text-muted-foreground",
	stages: "mt-4 grid w-full grid-cols-3 gap-2",
	bar: "h-2 rounded-full",
	activeBar: "bg-primary",
	completedBar: "bg-primary/50",
	pendingBar: "bg-muted",
	stageLabel: "mt-2 text-xs",
	pendingLabel: "text-muted-foreground",
	readyLabel: "font-medium text-foreground",
	actions: "flex flex-wrap gap-2",
} as const;
