export const projectsSurfaceClasses = {
	page: "space-y-6",
	smallIcon: "size-3.5",
	section: "space-y-3",
	shrinkContent: "min-w-0",
	fullHeight: "h-full",
} as const;

export const projectResourceCardClasses = {
	emoji: "text-xl",
} as const;

export const skillCardClasses = {
	removeAction: "text-muted-foreground hover:text-destructive",
	smallIcon: "size-3.5",
	body: "min-h-28 gap-2",
	iconTile: "rounded-lg text-base",
	badge: "shrink-0",
	projectChip: "inline-flex max-w-44 items-center gap-1 rounded-md bg-muted px-1.5 py-0.5",
	unselectable: "select-none",
	version: "font-mono",
} as const;

export const memoriesSurfaceClasses = {
	page: "space-y-6",
	filters: "flex-wrap justify-start",
	providerDescription: "text-xs text-muted-foreground",
	providerSkeleton: "h-11 w-36 sm:h-8",
	createSkeleton: "h-11 w-32 sm:h-8",
	content: "line-clamp-[8] break-words pr-10 text-sm leading-relaxed",
	footer: "mt-3 text-xs",
	source: "inline-flex min-w-0 items-center gap-1",
	sourceIcon: "size-3 shrink-0",
	sourceName: "max-w-28 truncate",
	actions: "absolute right-2 top-2",
	deleteAction: "bg-card/80 text-muted-foreground backdrop-blur-sm hover:text-destructive",
	smallIcon: "size-3.5",
	skeletonContent: "space-y-2",
	skeletonFooter: "mt-4 flex items-center gap-2",
	skeletonBadge: "h-5 w-24 rounded-full",
	skeletonCategory: "h-3 w-14",
	skeletonDate: "ml-auto h-3 w-20",
	pagination: "flex flex-wrap gap-2",
	pageSizeSkeleton: "h-11 w-56 sm:h-9",
	paginationSkeleton: "h-11 w-72 sm:h-9",
	loadingRow: "flex items-center gap-2 text-sm",
	loadingIcon: "size-4",
	section: "space-y-3",
	emptyHint: "text-sm text-muted-foreground",
	keyInput: "text-xs font-medium",
	keyHelp: "flex flex-col gap-2 sm:flex-row",
	fieldStack: "flex-1 font-mono",
	inputLabel: "w-full sm:w-auto",
	dialog: "sm:max-w-lg",
	field: "space-y-1.5",
	screenReaderOnly: "sr-only",
	textarea: "resize-none",
	fieldRow: "flex items-center gap-2",
	categorySelect: "w-32",
} as const;

export const vaultsSurfaceClasses = {
	smallIcon: "size-3.5",
	count: "text-muted-foreground tabular-nums",
	unselectable: "select-none",
	section: "space-y-2",
	description: "text-xs text-muted-foreground",
	skeletonCount: "h-3 w-12",
	fullHeight: "h-full",
	identity: "relative text-xl",
	sharedLock:
		"absolute -right-1 -bottom-1 flex size-4 items-center justify-center rounded-full border bg-card",
	lockIcon: "size-2.5 text-muted-foreground",
	truncate: "truncate",
	dialog: "sm:max-w-md",
	form: "space-y-4",
	field: "space-y-1.5",
	error: "text-xs text-destructive",
} as const;

export const connectorCardClasses = {
	rowHeight: "min-h-19",
	connectedIcon: "size-3.5 shrink-0 text-success",
} as const;

export const connectorsSurfaceClasses = {
	search: "h-10 w-full max-w-xl",
	section: "space-y-3",
	filters: "flex flex-wrap items-center gap-2",
	pagination: "flex items-center justify-center gap-2 pt-3",
	icon: "size-4",
	pageCount: "px-3 text-xs tabular-nums text-muted-foreground",
} as const;

export const projectDetailClasses = {
	statTile:
		"group rounded-xl border border-transparent p-4 transition-all duration-150 hover:-translate-y-px hover:border-foreground/20 focus-visible:ring-2 focus-visible:ring-ring focus:outline-none",
	statGrid: "grid grid-cols-2 gap-3 sm:grid-cols-4",
	statSkeleton: "h-24 w-full rounded-xl",
	panelSkeleton: "h-40 w-full rounded-lg",
	page: "space-y-6",
	emoji: "text-xl",
	smallButtonIcon: "mr-1.5 size-3.5",
	icon: "size-4",
	alertDescription: "flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between",
	tabs: "grid h-auto w-full grid-cols-5 gap-1 rounded-xl border bg-muted/30 p-1 group-data-horizontal/tabs:h-auto",
	tab: "min-w-0 px-1 py-2 text-xs sm:px-2 sm:text-sm",
	panel: "space-y-5",
	headingStack: "space-y-1",
	heading: "text-sm font-semibold",
	description: "text-sm text-muted-foreground",
	smallIcon: "size-3.5",
	rowSkeleton: "h-16 w-full",
	rowList: "divide-y overflow-hidden rounded-lg border bg-card",
	row: "flex items-center justify-between gap-3 px-4 py-3",
	rowName: "truncate text-sm",
	agentRow: "group relative flex items-center gap-3 px-4 py-3",
	grow: "min-w-0 flex-1",
	badge: "shrink-0",
	stretchedLink: "absolute inset-0 focus:outline-none focus-visible:ring-2 focus-visible:ring-ring",
	screenReaderOnly: "sr-only",
	statValue: "text-2xl font-semibold tabular-nums",
	statValueSkeleton: "h-8 w-8",
	statLabel: "mt-0.5 flex items-center gap-1 text-xs text-muted-foreground",
	statArrow: "size-3 opacity-0 transition-opacity duration-150 group-hover:opacity-100",
	pagination: "flex flex-wrap items-center justify-between gap-3 border-t pt-4",
	pageCount: "text-sm text-muted-foreground tabular-nums",
	paginationActions: "flex items-center gap-2",
	section: "scroll-mt-20 space-y-3",
	sectionHeader: "flex flex-col items-start gap-3 sm:flex-row sm:items-end sm:justify-between",
	shrinkContent: "min-w-0",
	tabular: "tabular-nums",
	subtitle: "mt-0.5 text-xs text-muted-foreground",
	muted: "text-muted-foreground",
	form: "space-y-4",
	mutedIcon: "size-4 text-muted-foreground",
	meta: "text-xs text-muted-foreground",
	inset: "rounded-md border bg-background/60 p-3",
	actionRow: "flex items-center justify-between gap-3",
	control: "flex-1",
	destructiveAction: "w-full text-muted-foreground hover:text-destructive",
	destructiveButton: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
	agentsDialog: "sm:max-w-lg",
	textarea: "h-24 w-full",
	agentChoices: "max-h-80 divide-y overflow-y-auto rounded-md border",
	agentChoice: "flex cursor-pointer items-center gap-3 px-3 py-2.5 hover:bg-muted/20",
	dialog: "sm:max-w-md",
	fieldStack: "grid gap-2",
	error: "text-xs text-destructive",
} as const;

export const skillDetailClasses = {
	loading: "space-y-3 py-2",
	removeAction: "text-destructive hover:text-destructive",
	projectLink: "inline-flex items-center gap-1 hover:text-foreground",
	smallIcon: "size-3",
	inlineMeta: "inline-flex items-center gap-1",
	panel: "space-y-3",
	panelHeading: "flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between",
	headingStack: "space-y-1",
	headingRow: "flex items-center gap-2",
	headingIcon: "size-4 text-muted-foreground",
	heading: "text-sm font-semibold",
	subtitle: "text-xs text-muted-foreground",
	projectCard: "rounded-md border bg-background/70 px-3 py-2.5",
	projectName: "text-sm font-medium",
	projectDescription: "mt-1 text-xs text-muted-foreground",
	instructionPanel: "space-y-4",
	field: "space-y-1.5",
	textarea: "min-h-[420px] text-sm leading-relaxed",
	markdown: "prose prose-sm max-w-none dark:prose-invert",
} as const;

export const memoryDetailClasses = {
	loading: "space-y-4 py-2",
	contentSkeleton: "h-24 w-full",
	metaSkeleton: "h-4 w-48",
	tabular: "tabular-nums",
	deleteAction: "w-fit shrink-0 text-destructive hover:text-destructive",
	panel: "space-y-4",
	headingStack: "space-y-1",
	heading: "text-sm font-semibold",
	subtitle: "text-xs text-muted-foreground",
	tags: "flex flex-wrap items-center gap-1.5",
	tag: "font-normal",
	provenance: "flex flex-wrap items-center gap-1.5 text-xs text-muted-foreground",
	smallIcon: "size-3",
	sessionLink: "underline hover:text-foreground",
} as const;

export const vaultDetailClasses = {
	keyCard:
		"group relative flex items-center gap-2 rounded-lg border bg-card px-3 py-2.5 transition-colors duration-150",
	projectCard: "flex items-center gap-3 rounded-lg border bg-card px-3 py-2.5",
	keysSkeleton: "h-36 w-full rounded-lg",
	projectsSkeleton: "h-24 w-full rounded-lg",
	emoji: "text-xl",
	destructive: "text-destructive",
	smallButtonIcon: "mr-1.5 size-3.5",
	section: "space-y-3",
	sectionHeader: "flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between",
	shrinkContent: "min-w-0",
	headingRow: "flex items-center gap-2",
	heading: "text-sm font-semibold",
	count: "tabular-nums",
	subtitle: "mt-0.5 text-xs text-muted-foreground",
	actions: "flex w-full flex-col gap-2 sm:w-auto sm:shrink-0 sm:flex-row sm:items-center",
	search: "h-8 w-full sm:w-52",
	control: "w-full sm:w-auto",
	smallIcon: "size-3.5",
	selectedCount: "h-6 w-fit px-2 text-xs",
	gridSkeleton: "h-32 w-full rounded-lg",
	keyGrid: "grid gap-2 sm:grid-cols-2 xl:grid-cols-3",
	checkbox: "pointer-events-none shrink-0",
	keyName: "min-w-0 flex-1 truncate font-mono text-xs",
	protectedValue: "shrink-0 font-mono text-3xs text-muted-foreground select-none",
	stretchedLink:
		"absolute inset-0 rounded-lg focus:outline-none focus-visible:ring-2 focus-visible:ring-ring",
	screenReaderOnly: "sr-only",
	removeKey:
		"text-muted-foreground opacity-100 transition-opacity duration-150 hover:text-destructive sm:opacity-0 sm:group-focus-within:opacity-100 sm:group-hover:opacity-100",
	tinyIcon: "size-3",
	projectSkeleton: "h-16 w-full",
	projectList: "divide-y overflow-hidden rounded-lg border bg-card",
	projectRow: "flex items-center gap-3 px-4 py-2.5",
	projectIdentity: "min-w-0 flex-1",
	projectLink: "block truncate text-sm font-medium hover:underline",
	projectName: "block text-sm font-medium",
	projectDescription: "truncate text-xs text-muted-foreground",
	detachAction: "text-muted-foreground hover:text-destructive",
	projectActions: "flex w-full flex-col gap-2 sm:w-auto sm:flex-row sm:items-center",
	projectSelect: "w-full sm:w-44",
} as const;

export const connectorDetailClasses = {
	toolRow: "flex items-start justify-between gap-3 px-3 py-2.5",
	accountRow: "flex flex-wrap items-center justify-between gap-2 px-3 py-2.5",
	accountHeader: "flex flex-wrap items-center justify-between gap-3 px-3 py-2.5",
	shrinkContent: "min-w-0",
	title: "truncate text-sm font-medium",
	subtitle: "truncate text-xs text-muted-foreground",
	hint: "mt-0.5 text-xs text-muted-foreground",
	actions: "flex flex-wrap items-center gap-2",
	disconnectAction: "shrink-0 text-destructive hover:bg-destructive/10 hover:text-destructive",
	smallIcon: "size-3.5",
	skeletonPadding: "p-4",
	identityRow: "flex items-center gap-3",
	iconSkeleton: "size-9 shrink-0 rounded-lg",
	identitySkeleton: "min-w-0 flex-1 space-y-2",
	titleSkeleton: "h-3.5 w-40",
	subtitleSkeleton: "h-3 w-28",
	divided: "divide-y",
	stack: "flex flex-col gap-4",
	section: "space-y-3",
	accountTitleSkeleton: "h-3.5 w-32",
	accountSubtitleSkeleton: "h-3 w-20",
	emptyAccount: "rounded-lg border border-dashed p-6",
	connectSkeleton: "mx-auto h-9 w-28 rounded-lg",
	bordered: "rounded-lg border",
	toolSkeleton: "h-3 w-56",
	loading: "flex items-center justify-center py-6",
	spinner: "size-5 text-muted-foreground",
	search: "w-full sm:w-56",
	toolList: "max-h-[32rem] overflow-y-auto",
	grow: "min-w-0 flex-1",
	toolHeading: "flex items-center gap-2",
	badge: "shrink-0",
	toolDescription: "mt-0.5 line-clamp-1 text-xs text-muted-foreground",
	emptyTools: "py-4 text-center text-sm text-muted-foreground",
} as const;

export const detailLayoutClasses = {
	meta: "flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground",
	stats: "flex flex-wrap items-center gap-x-4 gap-y-2",
	panel: "rounded-lg border bg-card/60 p-4",
	title: "font-semibold text-lg tracking-tight",
	page: "space-y-6 px-4 lg:px-6",
	detailPage: "space-y-5 px-4 lg:px-6",
	back: "w-fit",
} as const;
export const CONNECTOR_ICON_SIZES = {
	sm: { box: "size-6", pad: "p-0.5", text: "text-xs", radius: "rounded-md" },
	md: { box: "size-10", pad: "p-1.5", text: "text-base", radius: "rounded-lg" },
	lg: { box: "size-14", pad: "p-2", text: "text-2xl", radius: "rounded-xl" },
} as const;

export const connectorIconClasses = {
	root: "relative flex shrink-0 items-center justify-center overflow-hidden border",
	loaded: "bg-background",
	placeholder: "bg-muted",
	letter: "font-semibold text-muted-foreground",
	image: "absolute inset-0 h-full w-full object-contain transition-opacity",
} as const;
export const PROJECT_STAT_TILE_TINTS: Record<string, string> = {
	Skills: "bg-identity-2-bg/50",
	Vaults: "bg-identity-4-bg/50",
	People: "bg-identity-6-bg/50",
	Agents: "bg-identity-5-bg/50",
};

export const libraryNavigationClasses = {
	item: "group/command-item relative flex cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none in-data-[slot=dialog-content]:rounded-lg! data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 data-selected:bg-muted data-selected:text-foreground [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 data-selected:**:[svg]:text-foreground",
	row: "items-start gap-2 py-2.5",
	body: "flex min-w-0 flex-col gap-0.5",
	subtitle: "text-xs text-muted-foreground",
} as const;

export const shareProjectClasses = {
	content: "max-h-[calc(100dvh-2rem)] overflow-y-auto sm:max-w-lg",
	title: "pr-8 leading-snug break-words",
	panels: "space-y-4",
	section: "space-y-3",
	linksSection: "space-y-3 border-t pt-4",
	headingRow: "flex flex-wrap items-center justify-between gap-2",
	heading: "text-sm font-semibold",
	description: "text-sm text-muted-foreground",
	form: "flex gap-2",
	row: "flex items-center justify-between gap-2 py-1 text-sm",
	identity: "min-w-0",
	name: "truncate font-medium",
	meta: "text-xs text-muted-foreground",
	list: "space-y-2",
	linkMeta: "mt-1 flex flex-wrap items-center gap-x-3 text-xs text-muted-foreground",
	destructiveIcon: "size-3.5 text-destructive",
	freshLink: "mt-2 flex flex-col gap-2 sm:flex-row sm:items-center",
} as const;
