/** Verbatim Web recipes from components/notification-center; shared with native wrappers. */
export const notificationCenterClasses = {
	sectionHeader:
		"sticky top-0 z-10 border-b bg-popover/95 px-4 py-2 text-xs backdrop-blur-sm supports-backdrop-filter:bg-popover/85",
	sectionTitle: "font-medium text-muted-foreground",
	list: "divide-y",
	accountRow: "group relative px-4 py-3.5 transition-colors",
	accountRowNew: "bg-muted/35",
	newDot: "absolute top-5 left-1.5 size-1.5 rounded-full bg-primary",
	rowLayout: "flex items-start gap-3",
	rowBody: "min-w-0 flex-1",
	rowHead: "flex min-w-0 items-start justify-between gap-3",
	rowTitleGroup: "min-w-0",
	accountTitle: "text-sm",
	accountTitleNew: "font-semibold",
	accountTitleRead: "font-medium",
	time: "mt-0.5 block text-xs text-muted-foreground",
	rowTrailing: "flex shrink-0 items-center gap-1",
	description: "mt-2 text-xs text-muted-foreground leading-relaxed",
	action: "mt-3",
	invitationRow: "px-4 py-3.5",
	invitationName: "truncate text-sm font-semibold",
	invitationMeta: "mt-0.5 text-xs text-muted-foreground",
	invitationHandle: "font-mono",
	invitationActions: "mt-3 flex justify-end gap-1.5",
	sourceLoading: "flex items-center gap-2 border-b px-4 py-4 text-xs text-muted-foreground",
	sourceLoadingSpinner: "size-3.5",
	sourceError: "flex items-start gap-3 border-b px-4 py-4",
	sourceErrorTint: "bg-muted text-muted-foreground",
	sourceErrorTitle: "text-sm font-medium",
	sourceErrorDescription: "mt-0.5 text-xs text-muted-foreground leading-relaxed",
	sourceErrorRetry: "mt-2.5",
	empty: "flex min-h-48 flex-col items-center justify-center px-8 py-10 text-center",
	emptyIcon: "flex size-10 items-center justify-center rounded-full bg-muted text-muted-foreground",
	emptyGlyph: "size-4",
	emptyTitle: "mt-3 text-sm font-medium",
	emptyDescription: "mt-1 max-w-64 text-xs text-muted-foreground leading-relaxed",
	loadMore: "border-t px-4 py-3 text-center",
	severityTint: {
		info: undefined,
		warning: "bg-warning/10 text-warning-foreground",
		destructive: "bg-destructive/10 text-destructive",
	},
} as const;
