export const overviewComputeBodyClasses = {
	commercialRow: "grid grid-cols-[fit-content(40%)_minmax(0,1fr)] items-baseline gap-x-4",
	commercialLoadingRow: "items-center",
	commercialLabel: "min-w-0 break-words",
	commercialValue: "min-w-0 text-right break-words",
	commercialAccess: "col-span-full min-w-0 break-words",
	specSkeleton: "h-lh max-w-full",
	cpuSkeleton: "w-10",
	memorySkeleton: "w-16",
	storageSkeleton: "w-20",
	root: "space-y-2",
	plan: "text-sm text-muted-foreground",
	planSkeleton: "h-lh w-32 max-w-full",
	specs: "flex flex-wrap gap-x-1.5 gap-y-1 text-xs text-muted-foreground",
	screenReaderOnly: "sr-only",
	specValue: "flex items-center gap-1.5",
	commercial: "space-y-1 text-xs text-muted-foreground",
	commercialLabelSkeleton: "relative h-lh max-w-full",
	skeletonLabel: "invisible",
	commercialStatus: "inline-block max-w-full align-top",
	commercialStatusSkeleton: "h-lh w-16 max-w-full",
	actions: "flex flex-wrap justify-end gap-2 pt-1",
} as const;
