export const planComparisonClasses = {
	feature: "flex items-start gap-2 text-sm",
	featureIcon: "mt-0.5 size-4 shrink-0 text-success",
	price: "text-3xl font-semibold tracking-normal tabular-nums",
	unit: "text-xs text-muted-foreground tabular-nums",
	grid: "grid gap-3 lg:grid-cols-2",
	skeletonCard: "h-72 w-full rounded-lg",
	skeletonTitle: "w-56",
	header: "gap-2",
	title: "flex items-center gap-2",
	icon: "size-5 text-muted-foreground",
	priceBlock: "min-h-20 pt-1",
	description: "text-xs text-muted-foreground",
	subheading: "text-sm font-medium",
	stretch: "flex-1",
	features: "space-y-2",
	featuredCard: "border-primary/30",
	featuredIcon: "size-5 text-primary",
} as const;
