/** Verbatim Web recipes, shared with the native phone layout. */
export const sessionFeedClasses = {
	searchRole: "font-medium capitalize",
	rowHeight:
		"[--session-row-height:--spacing(20)] @3xl/main:[--session-row-height:--spacing(16.5)]",
	card: "flex min-h-(--session-row-height) min-w-0 items-center gap-3 px-4 py-3 transition-colors",
	overviewList: "grid gap-2",
	avatarSkeleton: "size-8 shrink-0 rounded-md",
	skeletonBody: "min-w-0 flex-1",
	skeletonTitle: "text-sm leading-5 font-semibold",
	titleSkeleton: "h-lh w-4/5",
	skeletonMeta: "mt-0.5 min-h-8 text-xs leading-4 @3xl/main:min-h-4",
	metaSkeleton: "h-lh w-1/2",
	secondaryMetaSkeleton: "h-lh w-1/3 @3xl/main:hidden",
	emptyRow: "justify-center border-dashed bg-muted/30 text-center text-sm text-muted-foreground",
	list: "flex flex-col gap-2",
	groups: "flex flex-col gap-5",
	project: "font-mono",
	root: "min-w-0",
	link: "group hover:bg-muted/50 focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background",
	automated: "bg-muted/30",
	avatar: "flex shrink-0",
	body: "w-0 min-w-0 flex-1",
	title: "block truncate text-sm leading-5 font-semibold",
	searchExcerpt: "mt-0.5 line-clamp-2 text-xs leading-4 text-foreground/75",
	meta: "mt-0.5 flex min-h-8 min-w-0 flex-wrap items-center gap-y-0 text-xs leading-4 text-muted-foreground @3xl/main:min-h-4",
	metaItem: "inline-flex min-w-0 max-w-full items-center",
	metaSeparator: "mx-1.5 shrink-0 text-muted-foreground/40",
	metaValue: "min-w-0 truncate",
} as const;
