/** Verbatim Web recipes from hosted/billing/usage/usage-page; shared with native wrappers. */
export const usagePageClasses = {
	agentFilter: "min-w-0 flex-1 sm:w-56 sm:flex-none",
	agentOption: "flex min-w-0 flex-1 items-center justify-between gap-3",
	rangeFilter: "min-w-0 flex-1 sm:w-40 sm:flex-none",
	pageEmpty: "py-10 md:p-10",
	totalsEmpty: "py-6 md:p-6",
	sectionEmpty: "py-4 md:p-4",
	summary: "grid overflow-hidden rounded-lg border sm:grid-cols-2 sm:divide-x",
	summaryCell: "space-y-1 p-4 sm:p-5",
	summaryCellNext: "space-y-1 border-t p-4 sm:border-t-0 sm:p-5",
	summaryLabel: "text-xs font-medium text-muted-foreground",
	summaryValue: "text-3xl font-semibold tracking-tight tabular-nums",
	chartPeakRow: "mb-3 flex justify-end text-xs text-muted-foreground",
	chartPeak: "font-medium tabular-nums text-foreground",
	chartBars: "flex h-36 items-end gap-px border-b sm:h-44 sm:gap-1",
	chartColumn: "group flex h-full min-w-0 flex-1 items-end",
	chartBar: "w-full rounded-t-sm bg-primary/75 group-hover:bg-primary",
	chartBarEmpty: "h-0.5 w-full bg-muted",
	chartAxis: "mt-2 flex justify-between text-xs text-muted-foreground",
	table: "w-full table-fixed",
	numericColumn: "w-[5.5rem] sm:w-28",
	headRow: "border-b text-xs text-muted-foreground",
	headCell: "pb-2 text-left font-medium",
	headNumericCell: "pb-2 text-right font-medium",
	body: "divide-y",
	modelCell: "min-w-0 py-3 pr-3 align-top",
	modelIdentity: "flex min-w-0 items-center gap-2",
	modelCopy: "min-w-0",
	modelName: "truncate text-sm font-medium",
	modelProvider: "truncate text-xs text-muted-foreground",
	requestsCell: "py-3 text-right align-top text-sm tabular-nums",
	spendCell: "py-3 text-right align-top text-sm font-medium tabular-nums",
} as const;
