export const vaultRequestClasses = {
	page: "mx-auto min-h-dvh w-full max-w-lg px-4 py-10",
	loading: "text-sm text-muted-foreground",
	card: "min-w-0 w-full",
	header: "gap-5",
	brand: "flex items-center gap-2",
	brandIcon: "size-7 shrink-0",
	brandName: "text-sm font-semibold tracking-tight",
	title: "text-xl font-semibold tracking-tight",
	muted: "text-muted-foreground",
	receipt: "select-text rounded-lg border bg-muted/30 p-3 text-sm leading-relaxed break-words",
	error: "text-sm text-destructive",
	footer: "flex justify-end",
	form: "space-y-5",
	context: "space-y-1 border-b pb-5 text-sm",
	contextTitle: "font-medium break-words",
	wrap: "break-words",
	fields: "min-w-0 space-y-5",
	field: "space-y-2",
	fieldHeader: "flex items-center justify-between gap-2",
	mono: "font-mono",
	update: "text-xs font-medium text-muted-foreground",
	actions: "flex gap-2",
	importPanel: "space-y-3 rounded-lg border p-3",
	preview: "text-sm",
	previewList: "space-y-2 text-sm",
	secretInput: "min-w-0 font-mono wrap-anywhere",
} as const;
