export const whatsappDeviceOnboardingClasses = {
	accountChoice: "flex min-w-0 flex-col gap-3",
	description: "text-xs text-muted-foreground [overflow-wrap:anywhere]",
	warning: "border-warning/30 bg-warning-muted py-2.5",
	warningDescription: "text-xs",
	readiness: "min-w-0 text-xs text-muted-foreground [overflow-wrap:anywhere]",
	connectAction: "w-full min-w-0 whitespace-normal sm:w-fit",
	connectIcon: "size-4 shrink-0",
	root: "min-w-0 space-y-4",
	actionIcon: "size-4",
	loadingIcon: "size-6",
	backAction: "inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground",
	nameField: "space-y-1.5",
	hint: "text-xs text-muted-foreground",
	statusWarning: "text-xs text-warning",
	doneAction: "w-full min-w-0 whitespace-normal",
	cancelAction: "w-full",
	successIcon: "size-7 text-success",
	expiredIcon: "size-7 text-warning",
	canceledIcon: "size-7 text-muted-foreground",
	errorIcon: "size-7 text-destructive",
	pairingCode: "space-y-3",
	pairingCodeTitle: "text-sm font-medium",
	pairingCodeHint: "mt-1 text-xs text-muted-foreground",
	instructionsTitle: "font-medium",
	scanHint: "text-xs text-muted-foreground sm:hidden",
	fallback: "rounded-lg border bg-muted/10 p-3",
	fallbackTitle: "cursor-pointer text-sm font-medium",
	fallbackContent: "mt-3 space-y-2",
	phoneError: "text-xs text-destructive",
	centeredState: "flex min-h-40 flex-col items-center justify-center gap-2 text-center",
	stateTitle: "max-w-full font-medium [overflow-wrap:anywhere]",
	stateDescription: "max-w-sm text-xs text-muted-foreground [overflow-wrap:anywhere]",
} as const;
