/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as SignUpSplatRouteImport } from './routes/sign-up/$'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as SChar123idChar125DotmdRouteImport } from './routes/s/{$id}[.]md'
import { Route as SChar123idChar125DotjsonRouteImport } from './routes/s/{$id}[.]json'
import { Route as SIdRouteImport } from './routes/s/$id'
import { Route as ProtectedCliAuthorizeRouteImport } from './routes/_protected/cli-authorize'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/_dashboard'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/_dashboard/index'
import { Route as ProtectedDashboardDeployRouteImport } from './routes/_protected/_dashboard/deploy'
import { Route as ProtectedDashboardAiProvidersRouteImport } from './routes/_protected/_dashboard/ai-providers'
import { Route as ProtectedDashboardVaultIndexRouteImport } from './routes/_protected/_dashboard/vault/index'
import { Route as ProtectedDashboardSkillsIndexRouteImport } from './routes/_protected/_dashboard/skills/index'
import { Route as ProtectedDashboardSessionsIndexRouteImport } from './routes/_protected/_dashboard/sessions/index'
import { Route as ProtectedDashboardProjectsIndexRouteImport } from './routes/_protected/_dashboard/projects/index'
import { Route as ProtectedDashboardMemoriesIndexRouteImport } from './routes/_protected/_dashboard/memories/index'
import { Route as ProtectedDashboardConnectorsIndexRouteImport } from './routes/_protected/_dashboard/connectors/index'
import { Route as ProtectedDashboardChannelsIndexRouteImport } from './routes/_protected/_dashboard/channels/index'
import { Route as ProtectedDashboardAgentsIndexRouteImport } from './routes/_protected/_dashboard/agents/index'
import { Route as ProtectedOauthCodexCallbackRouteImport } from './routes/_protected/oauth/codex/callback'
import { Route as ProtectedDashboardVaultSlugRouteImport } from './routes/_protected/_dashboard/vault/$slug'
import { Route as ProtectedDashboardSkillsKeyRouteImport } from './routes/_protected/_dashboard/skills/$key'
import { Route as ProtectedDashboardSessionsIdRouteImport } from './routes/_protected/_dashboard/sessions/$id'
import { Route as ProtectedDashboardProjectsIdRouteImport } from './routes/_protected/_dashboard/projects/$id'
import { Route as ProtectedDashboardMemoriesIdRouteImport } from './routes/_protected/_dashboard/memories/$id'
import { Route as ProtectedDashboardConnectorsNameRouteImport } from './routes/_protected/_dashboard/connectors/$name'
import { Route as ProtectedDashboardChannelsIdRouteImport } from './routes/_protected/_dashboard/channels/$id'
import { Route as ProtectedDashboardAgentsIdIndexRouteImport } from './routes/_protected/_dashboard/agents/$id/index'
import { Route as ProtectedDashboardAgentsIdSectionRouteImport } from './routes/_protected/_dashboard/agents/$id/$section'
import { Route as ProtectedDashboardAgentsIdSkillsIndexRouteImport } from './routes/_protected/_dashboard/agents/$id/skills/index'
import { Route as ProtectedDashboardAgentsIdSkillsSplatRouteImport } from './routes/_protected/_dashboard/agents/$id/skills/$'
import { Route as ProtectedDashboardAgentsIdSessionsSessionIdRouteImport } from './routes/_protected/_dashboard/agents/$id/sessions/$sessionId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SChar123idChar125DotmdRoute = SChar123idChar125DotmdRouteImport.update({
  id: '/s/{$id}.md',
  path: '/s/{$id}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const SChar123idChar125DotjsonRoute =
  SChar123idChar125DotjsonRouteImport.update({
    id: '/s/{$id}.json',
    path: '/s/{$id}.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCliAuthorizeRoute = ProtectedCliAuthorizeRouteImport.update({
  id: '/cli-authorize',
  path: '/cli-authorize',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ProtectedDashboardDeployRoute =
  ProtectedDashboardDeployRouteImport.update({
    id: '/deploy',
    path: '/deploy',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardAiProvidersRoute =
  ProtectedDashboardAiProvidersRouteImport.update({
    id: '/ai-providers',
    path: '/ai-providers',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardVaultIndexRoute =
  ProtectedDashboardVaultIndexRouteImport.update({
    id: '/vault/',
    path: '/vault/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardSkillsIndexRoute =
  ProtectedDashboardSkillsIndexRouteImport.update({
    id: '/skills/',
    path: '/skills/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardSessionsIndexRoute =
  ProtectedDashboardSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardProjectsIndexRoute =
  ProtectedDashboardProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardMemoriesIndexRoute =
  ProtectedDashboardMemoriesIndexRouteImport.update({
    id: '/memories/',
    path: '/memories/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardConnectorsIndexRoute =
  ProtectedDashboardConnectorsIndexRouteImport.update({
    id: '/connectors/',
    path: '/connectors/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardChannelsIndexRoute =
  ProtectedDashboardChannelsIndexRouteImport.update({
    id: '/channels/',
    path: '/channels/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardAgentsIndexRoute =
  ProtectedDashboardAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedOauthCodexCallbackRoute =
  ProtectedOauthCodexCallbackRouteImport.update({
    id: '/oauth/codex/callback',
    path: '/oauth/codex/callback',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardVaultSlugRoute =
  ProtectedDashboardVaultSlugRouteImport.update({
    id: '/vault/$slug',
    path: '/vault/$slug',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardSkillsKeyRoute =
  ProtectedDashboardSkillsKeyRouteImport.update({
    id: '/skills/$key',
    path: '/skills/$key',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardSessionsIdRoute =
  ProtectedDashboardSessionsIdRouteImport.update({
    id: '/sessions/$id',
    path: '/sessions/$id',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardProjectsIdRoute =
  ProtectedDashboardProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardMemoriesIdRoute =
  ProtectedDashboardMemoriesIdRouteImport.update({
    id: '/memories/$id',
    path: '/memories/$id',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardConnectorsNameRoute =
  ProtectedDashboardConnectorsNameRouteImport.update({
    id: '/connectors/$name',
    path: '/connectors/$name',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardChannelsIdRoute =
  ProtectedDashboardChannelsIdRouteImport.update({
    id: '/channels/$id',
    path: '/channels/$id',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardAgentsIdIndexRoute =
  ProtectedDashboardAgentsIdIndexRouteImport.update({
    id: '/agents/$id/',
    path: '/agents/$id/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardAgentsIdSectionRoute =
  ProtectedDashboardAgentsIdSectionRouteImport.update({
    id: '/agents/$id/$section',
    path: '/agents/$id/$section',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardAgentsIdSkillsIndexRoute =
  ProtectedDashboardAgentsIdSkillsIndexRouteImport.update({
    id: '/agents/$id/skills/',
    path: '/agents/$id/skills/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardAgentsIdSkillsSplatRoute =
  ProtectedDashboardAgentsIdSkillsSplatRouteImport.update({
    id: '/agents/$id/skills/$',
    path: '/agents/$id/skills/$',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardAgentsIdSessionsSessionIdRoute =
  ProtectedDashboardAgentsIdSessionsSessionIdRouteImport.update({
    id: '/agents/$id/sessions/$sessionId',
    path: '/agents/$id/sessions/$sessionId',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedDashboardIndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/cli-authorize': typeof ProtectedCliAuthorizeRoute
  '/s/$id': typeof SIdRoute
  '/s/{$id}.json': typeof SChar123idChar125DotjsonRoute
  '/s/{$id}.md': typeof SChar123idChar125DotmdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/ai-providers': typeof ProtectedDashboardAiProvidersRoute
  '/deploy': typeof ProtectedDashboardDeployRoute
  '/channels/$id': typeof ProtectedDashboardChannelsIdRoute
  '/connectors/$name': typeof ProtectedDashboardConnectorsNameRoute
  '/memories/$id': typeof ProtectedDashboardMemoriesIdRoute
  '/projects/$id': typeof ProtectedDashboardProjectsIdRoute
  '/sessions/$id': typeof ProtectedDashboardSessionsIdRoute
  '/skills/$key': typeof ProtectedDashboardSkillsKeyRoute
  '/vault/$slug': typeof ProtectedDashboardVaultSlugRoute
  '/oauth/codex/callback': typeof ProtectedOauthCodexCallbackRoute
  '/agents/': typeof ProtectedDashboardAgentsIndexRoute
  '/channels/': typeof ProtectedDashboardChannelsIndexRoute
  '/connectors/': typeof ProtectedDashboardConnectorsIndexRoute
  '/memories/': typeof ProtectedDashboardMemoriesIndexRoute
  '/projects/': typeof ProtectedDashboardProjectsIndexRoute
  '/sessions/': typeof ProtectedDashboardSessionsIndexRoute
  '/skills/': typeof ProtectedDashboardSkillsIndexRoute
  '/vault/': typeof ProtectedDashboardVaultIndexRoute
  '/agents/$id/$section': typeof ProtectedDashboardAgentsIdSectionRoute
  '/agents/$id/': typeof ProtectedDashboardAgentsIdIndexRoute
  '/agents/$id/sessions/$sessionId': typeof ProtectedDashboardAgentsIdSessionsSessionIdRoute
  '/agents/$id/skills/$': typeof ProtectedDashboardAgentsIdSkillsSplatRoute
  '/agents/$id/skills/': typeof ProtectedDashboardAgentsIdSkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedDashboardIndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/cli-authorize': typeof ProtectedCliAuthorizeRoute
  '/s/$id': typeof SIdRoute
  '/s/{$id}.json': typeof SChar123idChar125DotjsonRoute
  '/s/{$id}.md': typeof SChar123idChar125DotmdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/ai-providers': typeof ProtectedDashboardAiProvidersRoute
  '/deploy': typeof ProtectedDashboardDeployRoute
  '/channels/$id': typeof ProtectedDashboardChannelsIdRoute
  '/connectors/$name': typeof ProtectedDashboardConnectorsNameRoute
  '/memories/$id': typeof ProtectedDashboardMemoriesIdRoute
  '/projects/$id': typeof ProtectedDashboardProjectsIdRoute
  '/sessions/$id': typeof ProtectedDashboardSessionsIdRoute
  '/skills/$key': typeof ProtectedDashboardSkillsKeyRoute
  '/vault/$slug': typeof ProtectedDashboardVaultSlugRoute
  '/oauth/codex/callback': typeof ProtectedOauthCodexCallbackRoute
  '/agents': typeof ProtectedDashboardAgentsIndexRoute
  '/channels': typeof ProtectedDashboardChannelsIndexRoute
  '/connectors': typeof ProtectedDashboardConnectorsIndexRoute
  '/memories': typeof ProtectedDashboardMemoriesIndexRoute
  '/projects': typeof ProtectedDashboardProjectsIndexRoute
  '/sessions': typeof ProtectedDashboardSessionsIndexRoute
  '/skills': typeof ProtectedDashboardSkillsIndexRoute
  '/vault': typeof ProtectedDashboardVaultIndexRoute
  '/agents/$id/$section': typeof ProtectedDashboardAgentsIdSectionRoute
  '/agents/$id': typeof ProtectedDashboardAgentsIdIndexRoute
  '/agents/$id/sessions/$sessionId': typeof ProtectedDashboardAgentsIdSessionsSessionIdRoute
  '/agents/$id/skills/$': typeof ProtectedDashboardAgentsIdSkillsSplatRoute
  '/agents/$id/skills': typeof ProtectedDashboardAgentsIdSkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/_protected/_dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/cli-authorize': typeof ProtectedCliAuthorizeRoute
  '/s/$id': typeof SIdRoute
  '/s/{$id}.json': typeof SChar123idChar125DotjsonRoute
  '/s/{$id}.md': typeof SChar123idChar125DotmdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_protected/_dashboard/ai-providers': typeof ProtectedDashboardAiProvidersRoute
  '/_protected/_dashboard/deploy': typeof ProtectedDashboardDeployRoute
  '/_protected/_dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/_dashboard/channels/$id': typeof ProtectedDashboardChannelsIdRoute
  '/_protected/_dashboard/connectors/$name': typeof ProtectedDashboardConnectorsNameRoute
  '/_protected/_dashboard/memories/$id': typeof ProtectedDashboardMemoriesIdRoute
  '/_protected/_dashboard/projects/$id': typeof ProtectedDashboardProjectsIdRoute
  '/_protected/_dashboard/sessions/$id': typeof ProtectedDashboardSessionsIdRoute
  '/_protected/_dashboard/skills/$key': typeof ProtectedDashboardSkillsKeyRoute
  '/_protected/_dashboard/vault/$slug': typeof ProtectedDashboardVaultSlugRoute
  '/_protected/oauth/codex/callback': typeof ProtectedOauthCodexCallbackRoute
  '/_protected/_dashboard/agents/': typeof ProtectedDashboardAgentsIndexRoute
  '/_protected/_dashboard/channels/': typeof ProtectedDashboardChannelsIndexRoute
  '/_protected/_dashboard/connectors/': typeof ProtectedDashboardConnectorsIndexRoute
  '/_protected/_dashboard/memories/': typeof ProtectedDashboardMemoriesIndexRoute
  '/_protected/_dashboard/projects/': typeof ProtectedDashboardProjectsIndexRoute
  '/_protected/_dashboard/sessions/': typeof ProtectedDashboardSessionsIndexRoute
  '/_protected/_dashboard/skills/': typeof ProtectedDashboardSkillsIndexRoute
  '/_protected/_dashboard/vault/': typeof ProtectedDashboardVaultIndexRoute
  '/_protected/_dashboard/agents/$id/$section': typeof ProtectedDashboardAgentsIdSectionRoute
  '/_protected/_dashboard/agents/$id/': typeof ProtectedDashboardAgentsIdIndexRoute
  '/_protected/_dashboard/agents/$id/sessions/$sessionId': typeof ProtectedDashboardAgentsIdSessionsSessionIdRoute
  '/_protected/_dashboard/agents/$id/skills/$': typeof ProtectedDashboardAgentsIdSkillsSplatRoute
  '/_protected/_dashboard/agents/$id/skills/': typeof ProtectedDashboardAgentsIdSkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/cli-authorize'
    | '/s/$id'
    | '/s/{$id}.json'
    | '/s/{$id}.md'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/ai-providers'
    | '/deploy'
    | '/channels/$id'
    | '/connectors/$name'
    | '/memories/$id'
    | '/projects/$id'
    | '/sessions/$id'
    | '/skills/$key'
    | '/vault/$slug'
    | '/oauth/codex/callback'
    | '/agents/'
    | '/channels/'
    | '/connectors/'
    | '/memories/'
    | '/projects/'
    | '/sessions/'
    | '/skills/'
    | '/vault/'
    | '/agents/$id/$section'
    | '/agents/$id/'
    | '/agents/$id/sessions/$sessionId'
    | '/agents/$id/skills/$'
    | '/agents/$id/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/cli-authorize'
    | '/s/$id'
    | '/s/{$id}.json'
    | '/s/{$id}.md'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/ai-providers'
    | '/deploy'
    | '/channels/$id'
    | '/connectors/$name'
    | '/memories/$id'
    | '/projects/$id'
    | '/sessions/$id'
    | '/skills/$key'
    | '/vault/$slug'
    | '/oauth/codex/callback'
    | '/agents'
    | '/channels'
    | '/connectors'
    | '/memories'
    | '/projects'
    | '/sessions'
    | '/skills'
    | '/vault'
    | '/agents/$id/$section'
    | '/agents/$id'
    | '/agents/$id/sessions/$sessionId'
    | '/agents/$id/skills/$'
    | '/agents/$id/skills'
  id:
    | '__root__'
    | '/_protected'
    | '/sign-in'
    | '/sign-up'
    | '/_protected/_dashboard'
    | '/_protected/cli-authorize'
    | '/s/$id'
    | '/s/{$id}.json'
    | '/s/{$id}.md'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_protected/_dashboard/ai-providers'
    | '/_protected/_dashboard/deploy'
    | '/_protected/_dashboard/'
    | '/_protected/_dashboard/channels/$id'
    | '/_protected/_dashboard/connectors/$name'
    | '/_protected/_dashboard/memories/$id'
    | '/_protected/_dashboard/projects/$id'
    | '/_protected/_dashboard/sessions/$id'
    | '/_protected/_dashboard/skills/$key'
    | '/_protected/_dashboard/vault/$slug'
    | '/_protected/oauth/codex/callback'
    | '/_protected/_dashboard/agents/'
    | '/_protected/_dashboard/channels/'
    | '/_protected/_dashboard/connectors/'
    | '/_protected/_dashboard/memories/'
    | '/_protected/_dashboard/projects/'
    | '/_protected/_dashboard/sessions/'
    | '/_protected/_dashboard/skills/'
    | '/_protected/_dashboard/vault/'
    | '/_protected/_dashboard/agents/$id/$section'
    | '/_protected/_dashboard/agents/$id/'
    | '/_protected/_dashboard/agents/$id/sessions/$sessionId'
    | '/_protected/_dashboard/agents/$id/skills/$'
    | '/_protected/_dashboard/agents/$id/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  SIdRoute: typeof SIdRoute
  SChar123idChar125DotjsonRoute: typeof SChar123idChar125DotjsonRoute
  SChar123idChar125DotmdRoute: typeof SChar123idChar125DotmdRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/{$id}.md': {
      id: '/s/{$id}.md'
      path: '/s/{$id}.md'
      fullPath: '/s/{$id}.md'
      preLoaderRoute: typeof SChar123idChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/{$id}.json': {
      id: '/s/{$id}.json'
      path: '/s/{$id}.json'
      fullPath: '/s/{$id}.json'
      preLoaderRoute: typeof SChar123idChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/cli-authorize': {
      id: '/_protected/cli-authorize'
      path: '/cli-authorize'
      fullPath: '/cli-authorize'
      preLoaderRoute: typeof ProtectedCliAuthorizeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_dashboard': {
      id: '/_protected/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_dashboard/': {
      id: '/_protected/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/deploy': {
      id: '/_protected/_dashboard/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof ProtectedDashboardDeployRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/ai-providers': {
      id: '/_protected/_dashboard/ai-providers'
      path: '/ai-providers'
      fullPath: '/ai-providers'
      preLoaderRoute: typeof ProtectedDashboardAiProvidersRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/vault/': {
      id: '/_protected/_dashboard/vault/'
      path: '/vault'
      fullPath: '/vault/'
      preLoaderRoute: typeof ProtectedDashboardVaultIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/skills/': {
      id: '/_protected/_dashboard/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof ProtectedDashboardSkillsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/sessions/': {
      id: '/_protected/_dashboard/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof ProtectedDashboardSessionsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/projects/': {
      id: '/_protected/_dashboard/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProtectedDashboardProjectsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/memories/': {
      id: '/_protected/_dashboard/memories/'
      path: '/memories'
      fullPath: '/memories/'
      preLoaderRoute: typeof ProtectedDashboardMemoriesIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/connectors/': {
      id: '/_protected/_dashboard/connectors/'
      path: '/connectors'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ProtectedDashboardConnectorsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/channels/': {
      id: '/_protected/_dashboard/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof ProtectedDashboardChannelsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/agents/': {
      id: '/_protected/_dashboard/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof ProtectedDashboardAgentsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/oauth/codex/callback': {
      id: '/_protected/oauth/codex/callback'
      path: '/oauth/codex/callback'
      fullPath: '/oauth/codex/callback'
      preLoaderRoute: typeof ProtectedOauthCodexCallbackRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_dashboard/vault/$slug': {
      id: '/_protected/_dashboard/vault/$slug'
      path: '/vault/$slug'
      fullPath: '/vault/$slug'
      preLoaderRoute: typeof ProtectedDashboardVaultSlugRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/skills/$key': {
      id: '/_protected/_dashboard/skills/$key'
      path: '/skills/$key'
      fullPath: '/skills/$key'
      preLoaderRoute: typeof ProtectedDashboardSkillsKeyRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/sessions/$id': {
      id: '/_protected/_dashboard/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof ProtectedDashboardSessionsIdRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/projects/$id': {
      id: '/_protected/_dashboard/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProtectedDashboardProjectsIdRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/memories/$id': {
      id: '/_protected/_dashboard/memories/$id'
      path: '/memories/$id'
      fullPath: '/memories/$id'
      preLoaderRoute: typeof ProtectedDashboardMemoriesIdRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/connectors/$name': {
      id: '/_protected/_dashboard/connectors/$name'
      path: '/connectors/$name'
      fullPath: '/connectors/$name'
      preLoaderRoute: typeof ProtectedDashboardConnectorsNameRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/channels/$id': {
      id: '/_protected/_dashboard/channels/$id'
      path: '/channels/$id'
      fullPath: '/channels/$id'
      preLoaderRoute: typeof ProtectedDashboardChannelsIdRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/agents/$id/': {
      id: '/_protected/_dashboard/agents/$id/'
      path: '/agents/$id'
      fullPath: '/agents/$id/'
      preLoaderRoute: typeof ProtectedDashboardAgentsIdIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/agents/$id/$section': {
      id: '/_protected/_dashboard/agents/$id/$section'
      path: '/agents/$id/$section'
      fullPath: '/agents/$id/$section'
      preLoaderRoute: typeof ProtectedDashboardAgentsIdSectionRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/agents/$id/skills/': {
      id: '/_protected/_dashboard/agents/$id/skills/'
      path: '/agents/$id/skills'
      fullPath: '/agents/$id/skills/'
      preLoaderRoute: typeof ProtectedDashboardAgentsIdSkillsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/agents/$id/skills/$': {
      id: '/_protected/_dashboard/agents/$id/skills/$'
      path: '/agents/$id/skills/$'
      fullPath: '/agents/$id/skills/$'
      preLoaderRoute: typeof ProtectedDashboardAgentsIdSkillsSplatRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/agents/$id/sessions/$sessionId': {
      id: '/_protected/_dashboard/agents/$id/sessions/$sessionId'
      path: '/agents/$id/sessions/$sessionId'
      fullPath: '/agents/$id/sessions/$sessionId'
      preLoaderRoute: typeof ProtectedDashboardAgentsIdSessionsSessionIdRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
  }
}

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardAiProvidersRoute: typeof ProtectedDashboardAiProvidersRoute
  ProtectedDashboardDeployRoute: typeof ProtectedDashboardDeployRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedDashboardChannelsIdRoute: typeof ProtectedDashboardChannelsIdRoute
  ProtectedDashboardConnectorsNameRoute: typeof ProtectedDashboardConnectorsNameRoute
  ProtectedDashboardMemoriesIdRoute: typeof ProtectedDashboardMemoriesIdRoute
  ProtectedDashboardProjectsIdRoute: typeof ProtectedDashboardProjectsIdRoute
  ProtectedDashboardSessionsIdRoute: typeof ProtectedDashboardSessionsIdRoute
  ProtectedDashboardSkillsKeyRoute: typeof ProtectedDashboardSkillsKeyRoute
  ProtectedDashboardVaultSlugRoute: typeof ProtectedDashboardVaultSlugRoute
  ProtectedDashboardAgentsIndexRoute: typeof ProtectedDashboardAgentsIndexRoute
  ProtectedDashboardChannelsIndexRoute: typeof ProtectedDashboardChannelsIndexRoute
  ProtectedDashboardConnectorsIndexRoute: typeof ProtectedDashboardConnectorsIndexRoute
  ProtectedDashboardMemoriesIndexRoute: typeof ProtectedDashboardMemoriesIndexRoute
  ProtectedDashboardProjectsIndexRoute: typeof ProtectedDashboardProjectsIndexRoute
  ProtectedDashboardSessionsIndexRoute: typeof ProtectedDashboardSessionsIndexRoute
  ProtectedDashboardSkillsIndexRoute: typeof ProtectedDashboardSkillsIndexRoute
  ProtectedDashboardVaultIndexRoute: typeof ProtectedDashboardVaultIndexRoute
  ProtectedDashboardAgentsIdSectionRoute: typeof ProtectedDashboardAgentsIdSectionRoute
  ProtectedDashboardAgentsIdIndexRoute: typeof ProtectedDashboardAgentsIdIndexRoute
  ProtectedDashboardAgentsIdSessionsSessionIdRoute: typeof ProtectedDashboardAgentsIdSessionsSessionIdRoute
  ProtectedDashboardAgentsIdSkillsSplatRoute: typeof ProtectedDashboardAgentsIdSkillsSplatRoute
  ProtectedDashboardAgentsIdSkillsIndexRoute: typeof ProtectedDashboardAgentsIdSkillsIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardAiProvidersRoute: ProtectedDashboardAiProvidersRoute,
  ProtectedDashboardDeployRoute: ProtectedDashboardDeployRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedDashboardChannelsIdRoute: ProtectedDashboardChannelsIdRoute,
  ProtectedDashboardConnectorsNameRoute: ProtectedDashboardConnectorsNameRoute,
  ProtectedDashboardMemoriesIdRoute: ProtectedDashboardMemoriesIdRoute,
  ProtectedDashboardProjectsIdRoute: ProtectedDashboardProjectsIdRoute,
  ProtectedDashboardSessionsIdRoute: ProtectedDashboardSessionsIdRoute,
  ProtectedDashboardSkillsKeyRoute: ProtectedDashboardSkillsKeyRoute,
  ProtectedDashboardVaultSlugRoute: ProtectedDashboardVaultSlugRoute,
  ProtectedDashboardAgentsIndexRoute: ProtectedDashboardAgentsIndexRoute,
  ProtectedDashboardChannelsIndexRoute: ProtectedDashboardChannelsIndexRoute,
  ProtectedDashboardConnectorsIndexRoute:
    ProtectedDashboardConnectorsIndexRoute,
  ProtectedDashboardMemoriesIndexRoute: ProtectedDashboardMemoriesIndexRoute,
  ProtectedDashboardProjectsIndexRoute: ProtectedDashboardProjectsIndexRoute,
  ProtectedDashboardSessionsIndexRoute: ProtectedDashboardSessionsIndexRoute,
  ProtectedDashboardSkillsIndexRoute: ProtectedDashboardSkillsIndexRoute,
  ProtectedDashboardVaultIndexRoute: ProtectedDashboardVaultIndexRoute,
  ProtectedDashboardAgentsIdSectionRoute:
    ProtectedDashboardAgentsIdSectionRoute,
  ProtectedDashboardAgentsIdIndexRoute: ProtectedDashboardAgentsIdIndexRoute,
  ProtectedDashboardAgentsIdSessionsSessionIdRoute:
    ProtectedDashboardAgentsIdSessionsSessionIdRoute,
  ProtectedDashboardAgentsIdSkillsSplatRoute:
    ProtectedDashboardAgentsIdSkillsSplatRoute,
  ProtectedDashboardAgentsIdSkillsIndexRoute:
    ProtectedDashboardAgentsIdSkillsIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
  ProtectedCliAuthorizeRoute: typeof ProtectedCliAuthorizeRoute
  ProtectedOauthCodexCallbackRoute: typeof ProtectedOauthCodexCallbackRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
  ProtectedCliAuthorizeRoute: ProtectedCliAuthorizeRoute,
  ProtectedOauthCodexCallbackRoute: ProtectedOauthCodexCallbackRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  SIdRoute: SIdRoute,
  SChar123idChar125DotjsonRoute: SChar123idChar125DotjsonRoute,
  SChar123idChar125DotmdRoute: SChar123idChar125DotmdRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
