/* Central icon re-export — lucide is the only icon set (DESIGN.md).
 *
 * Import icons from "@/components/icons" instead of "lucide-react" so the
 * app has one place to swap/curate icons. Stroke weight is pinned globally
 * via `svg.lucide { stroke-width: 1.75 }` in the shared theme; size comes
 * from the consuming primitive (buttons/badges pin size-4/size-3).
 *
 * Add icons here as pages migrate; keep the list alphabetical. */

export type { LucideIcon } from "lucide-react";
export {
	AlertCircle,
	AlertTriangle,
	ArrowDown,
	ArrowRight,
	ArrowUp,
	ArrowUpRight,
	Bot,
	Brain,
	Check,
	CheckCircle2,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronsLeft,
	ChevronsRight,
	ChevronsUpDown,
	ChevronUp,
	Circle,
	Clock,
	Cloud,
	Copy,
	Database,
	ExternalLink,
	FileJson,
	FileText,
	FolderKanban,
	GitBranch,
	GitPullRequest,
	Globe2,
	Hash,
	Inbox,
	Key,
	Laptop,
	Link2,
	Link2Off,
	Loader2,
	Lock,
	LogOut,
	MailOpen,
	MessageSquare,
	Monitor,
	Moon,
	MoreHorizontal,
	Package,
	PanelLeft,
	Plug,
	Plus,
	PlusCircle,
	Rocket,
	RotateCcw,
	Search,
	Settings,
	Share2,
	ShieldCheck,
	Sparkles,
	Sun,
	Terminal,
	Trash2,
	Upload,
	User,
	Workflow,
	Wrench,
	X,
	XCircle,
	Zap,
} from "lucide-react";
