export const channelsEn = {
	create: "Add Custom bot",
	name: "Bot name",
	token: "Bot token",
	applicationId: "Discord application ID",
	publicKey: "Discord interactions public key",
	createInstructions:
		"Use a Telegram token from BotFather, or Discord bot credentials from the developer portal. The bot is added without an Agent; linking and pairing are separate actions.",
	createUncertain:
		"This bot may already have been created. Refresh and inspect inventory before submitting again. Closing this form does not undo a request already sent.",
	reviewInventory: "Refresh inventory before another submission",
	title: "Channels",
	description: "Manage Custom bots, shared bots, Agent links and paired chats.",
	empty: "No channels available.",
	details: "Manage channel",
	shared: "Shared bot",
	custom: "Custom bot",
	links: "Linked Agents",
	link: "Link selected Agent",
	replace: "Replace this Agent's existing channel for this provider",
	replaceWarning:
		"Replacement disconnects the previous bot for this provider. Paired chats may lose access.",
	selectAgent: "Select an Agent",
	unlink: "Unlink Agent",
	pair: "Generate chat pairing code",
	pairInstructions:
		"Use this command in the intended chat. Codes expire after five minutes. Refresh paired chats to confirm; opening a link is not proof of pairing.",
	pairExpired: "Pairing code expired. Generate a new code.",
	openPair: "Open pairing link",
	install: "Install Discord bot",
	installUser: "Install Discord app for user",
	bindings: "Paired chats",
	noBindings: "No paired chats.",
	unpair: "Unpair chat",
	unpairWarning: "This chat will no longer be connected to the Agent.",
	cleanupWarning:
		"Chat access was revoked, but notification or provider cleanup is incomplete. Refresh to inspect the result.",
	unpairNotConfirmed: "Unpairing was not confirmed. Refresh paired chats before trying again.",
	activity: "Recent activity (up to 50 events)",
	remove: "Delete Custom bot",
	removeWarning: "Deleting this bot disconnects its Agents and chats. This cannot be undone.",
	sync: "Sync channel commands",
	done: "Action confirmed. Refresh to inspect current state.",
	failed:
		"The action was not confirmed. Refresh before trying again. Channel availability, capacity or runtime permissions may have changed.",
	unavailable:
		"Channel permissions or availability could not be confirmed. Refresh before making changes.",
	refresh: "Refresh channels",
	health: "Channel health",
	ok: "Healthy",
	warning: "Needs attention",
	error: "Unhealthy",
	unknown: "Health unavailable",
};
