export const DESKTOP_IPC = {
	signOut: "clawdi:sign-out",
	openConnector: "clawdi:open-connector",
	createDashboardSession: "clawdi:create-dashboard-session",
	bootstrapState: "clawdi:bootstrap-state",
	authenticate: "clawdi:authenticate",
	authenticationProgress: "clawdi:authentication-progress",
	cancelAuthentication: "clawdi:cancel-authentication",
	reopenVerificationPage: "clawdi:reopen-verification-page",
	takeRequestedView: "clawdi:take-requested-view",
	viewRequested: "clawdi:view-requested",
	listExcludedProjects: "clawdi:list-excluded-projects",
	addExcludedProject: "clawdi:add-excluded-project",
	removeExcludedProject: "clawdi:remove-excluded-project",
	detectAgents: "clawdi:detect-agents",
	listReconnectableAgents: "clawdi:list-reconnectable-agents",
	installationState: "clawdi:installation-state",
	connectAgents: "clawdi:connect-agents",
	moveToApplicationsFolder: "clawdi:move-to-applications-folder",
	openDashboard: "clawdi:open-dashboard",
} as const;
