export const DESKTOP_IPC = {
	bootstrapState: "clawdi:bootstrap-state",
	authenticate: "clawdi:authenticate",
	cancelAuthentication: "clawdi:cancel-authentication",
	detectAgents: "clawdi:detect-agents",
	listReconnectableAgents: "clawdi:list-reconnectable-agents",
	installationState: "clawdi:installation-state",
	connectAgents: "clawdi:connect-agents",
	moveToApplicationsFolder: "clawdi:move-to-applications-folder",
	signIn: "clawdi:sign-in",
	signOut: "clawdi:sign-out",
	openConnectWizard: "clawdi:open-connect-wizard",
	openDashboard: "clawdi:open-dashboard",
	retryDashboard: "clawdi:retry-dashboard",
} as const;
