import { afterEach, test as bunTest, expect } from "bun:test";
import {
	cpSync,
	existsSync,
	mkdirSync,
	mkdtempSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { parse } from "yaml";

const roots: string[] = [];
// The Pages publisher runs on Linux; its fixture implements gh as a POSIX script.
const test = bunTest.skipIf(process.platform === "win32");
afterEach(() => {
	for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function fixture(missingAsset = false) {
	const root = mkdtempSync(join(tmpdir(), "desktop-update-site-"));
	roots.push(root);
	mkdirSync(join(root, "bin"));
	mkdirSync(join(root, "live"));
	const release = (version: string, prerelease: boolean) => ({
		tag_name: `desktop-v${version}`,
		prerelease,
		draft: false,
		published_at: "2020-01-01T00:00:00Z",
		assets: [
			{ name: prerelease ? "beta-mac.yml" : "latest-mac.yml", id: 1 },
			{ name: prerelease ? "beta-mac-x64.yml" : "latest-mac-x64.yml", id: prerelease ? 1 : 2 },
			...(missingAsset ? [] : [{ name: "Clawdi.zip" }]),
		],
	});
	// Different metadata per request is supplied by the fake gh using the selected asset ID.
	const stable = release("1.0.0", false);
	stable.assets[0] = { name: "latest-mac.yml", id: 2 };
	writeFileSync(
		join(root, "releases.json"),
		JSON.stringify([
			[{ tag_name: "clawdi-cli-v99.0.0", draft: false }, release("1.1.0-beta.2", true)],
			[release("1.1.0-beta.10", true), stable],
		]),
	);
	writeFileSync(
		join(root, "metadata.json"),
		JSON.stringify({
			version: "1.1.0-beta.10",
			path: "Clawdi.zip",
			files: [{ url: "Clawdi.zip", sha512: "hash", size: 1 }],
		}),
	);
	writeFileSync(
		join(root, "stable.json"),
		JSON.stringify({
			version: "1.0.0",
			path: "Clawdi.zip",
			files: [{ url: "Clawdi.zip", sha512: "hash", size: 1 }],
		}),
	);
	writeFileSync(
		join(root, "bin", "gh"),
		'#!/bin/sh\ncase "$2" in\n  */assets/2) cat "$FIXTURE_ROOT/stable.json" ;;\n  *releases/assets/*) cat "$FIXTURE_ROOT/metadata.json" ;;\n  *) cat "$FIXTURE_ROOT/releases.json" ;;\nesac\n',
		{ mode: 0o700 },
	);
	// Stub only curl's network boundary; exercise the real comparison script and output.
	writeFileSync(
		join(root, "bin", "curl"),
		`#!/bin/sh
for argument do url="$argument"; done
path="\${url#https://example.invalid/project/}"
case "$path" in https:*) exit 2 ;; esac
if [ -n "$CURL_FAILURE_PATH" ] && [ "$path" = "$CURL_FAILURE_PATH" ]; then
  if [ "$CURL_FAILURE" = transport ]; then exit 7; fi
  printf '\\n%s' "$CURL_FAILURE"
elif [ -f "$FIXTURE_ROOT/live/$path" ]; then
  cat "$FIXTURE_ROOT/live/$path"
  printf '\\n200'
else
  printf 'Not found\\n404'
fi
`,
		{ mode: 0o700 },
	);
	return root;
}

async function prepare(root: string, paused = "") {
	const child = Bun.spawn(
		[
			process.execPath,
			resolve(import.meta.dir, "../scripts/prepare-update-site.ts"),
			join(root, "site"),
		],
		{
			env: {
				...process.env,
				PATH: `${join(root, "bin")}:${process.env.PATH}`,
				FIXTURE_ROOT: root,
				GITHUB_REPOSITORY: "owner/repo",
				DESKTOP_PAUSED_VERSIONS: paused,
				DESKTOP_UPDATE_SITE_URL: "",
			},
			stdout: "pipe",
			stderr: "pipe",
		},
	);
	return { code: await child.exited, error: await new Response(child.stderr).text() };
}

async function compare(root: string, failure = "", failurePath = "") {
	const output = join(root, "github-output");
	rmSync(output, { force: true });
	const child = Bun.spawn(
		[
			process.execPath,
			resolve(import.meta.dir, "../scripts/compare-update-site.ts"),
			join(root, "site"),
		],
		{
			env: {
				...process.env,
				PATH: `${join(root, "bin")}:${process.env.PATH}`,
				FIXTURE_ROOT: root,
				DESKTOP_UPDATE_SITE_URL: "https://example.invalid/project/",
				GITHUB_OUTPUT: output,
				CURL_FAILURE: failure,
				CURL_FAILURE_PATH: failurePath,
			},
			stdout: "pipe",
			stderr: "pipe",
		},
	);
	return {
		code: await child.exited,
		error: await new Response(child.stderr).text(),
		output: existsSync(output) ? readFileSync(output, "utf8") : "",
	};
}

test("Pages skips identical prepared content, including other site files", async () => {
	const root = fixture();
	expect((await prepare(root)).code).toBe(0);
	mkdirSync(join(root, "site/downloads"));
	writeFileSync(join(root, "site/downloads/index.html"), "Download Clawdi\n");
	cpSync(join(root, "site"), join(root, "live"), { recursive: true });
	writeFileSync(join(root, "live/unrelated.html"), "Not generated by this publisher");
	const result = await compare(root);
	expect(result.code).toBe(0);
	expect(result.output).toBe("changed=false\n");

	for (const path of ["index.html", "desktop/latest-mac.yml", "downloads/index.html"]) {
		const original = readFileSync(join(root, "live", path));
		writeFileSync(join(root, "live", path), "Changed content\n");
		expect((await compare(root)).output).toBe("changed=true\n");
		writeFileSync(join(root, "live", path), original);
	}
});

test("Pages deploys when a generated file returns 404, including first publication", async () => {
	const root = fixture();
	expect((await prepare(root)).code).toBe(0);
	expect((await compare(root)).output).toBe("changed=true\n");
	cpSync(join(root, "site"), join(root, "live"), { recursive: true });
	for (const path of ["desktop/darwin-x64/beta-mac.yml", "index.html"]) {
		const original = readFileSync(join(root, "live", path));
		rmSync(join(root, "live", path));
		expect((await compare(root)).output).toBe("changed=true\n");
		writeFileSync(join(root, "live", path), original);
	}
});

test("Pages deploys feed deletion for a pause and skips feeds already absent", async () => {
	const root = fixture();
	expect((await prepare(root)).code).toBe(0);
	cpSync(join(root, "site"), join(root, "live"), { recursive: true });
	expect((await prepare(root, "1.0.0,1.1.0-beta.2,1.1.0-beta.10")).code).toBe(0);
	expect((await compare(root)).output).toBe("changed=true\n");
	rmSync(join(root, "live/desktop"), { recursive: true });
	expect((await compare(root)).output).toBe("changed=false\n");
	// An omitted Windows feed is managed too, even though this release predates Windows.
	mkdirSync(join(root, "live/desktop/win32-arm64"), { recursive: true });
	writeFileSync(join(root, "live/desktop/win32-arm64/latest.yml"), "version: 1.0.0\n");
	expect((await compare(root)).output).toBe("changed=true\n");
});

test("Pages comparison fails closed on HTTP and transport errors, even after a change", async () => {
	const root = fixture();
	expect((await prepare(root)).code).toBe(0);
	for (const failure of ["503", "transport"]) {
		const result = await compare(root, failure, "desktop/win32-x64/beta.yml");
		expect(result.code).not.toBe(0);
		expect(result.error).not.toBe("");
		expect(result.output).toBe("");
	}
});

test("Pages keeps both channels, paginates releases and selects semantic versions", async () => {
	const root = fixture();
	expect((await prepare(root)).code).toBe(0);
	for (const [file, version] of [
		["latest-mac.yml", "1.0.0"],
		["beta-mac.yml", "1.1.0-beta.10"],
	] as const) {
		const metadata = parse(readFileSync(join(root, "site/desktop", file), "utf8"));
		expect(metadata.version).toBe(version);
		expect(metadata.stagingPercentage).toBe(file.startsWith("latest") ? 100 : undefined);
		expect(metadata.files[0].url).toBe(
			`https://github.com/owner/repo/releases/download/desktop-v${version}/Clawdi.zip`,
		);
		expect(metadata.path).toBe(metadata.files[0].url);
		const intel = parse(readFileSync(join(root, "site/desktop/darwin-x64", file), "utf8"));
		expect(intel.version).toBe(version);
	}
});

test("all paused channels remove metadata, and regeneration is idempotent", async () => {
	const root = fixture();
	expect((await prepare(root)).code).toBe(0);
	const previous = readFileSync(join(root, "site/desktop/latest-mac.yml"), "utf8");
	expect((await prepare(root)).code).toBe(0);
	expect(readFileSync(join(root, "site/desktop/latest-mac.yml"), "utf8")).toBe(previous);
	expect((await prepare(root, "1.0.0,1.1.0-beta.2,1.1.0-beta.10")).code).toBe(0);
	expect(existsSync(join(root, "site/desktop/latest-mac.yml"))).toBe(false);
	expect(existsSync(join(root, "site/desktop/beta-mac.yml"))).toBe(false);
});

test("Pages refuses metadata pointing to an absent release artifact", async () => {
	const result = await prepare(fixture(true));
	expect(result.code).not.toBe(0);
	expect(result.error).toContain("Missing artifact");
});

test("Pages isolates Windows and Linux architectures and rejects partial matrices", async () => {
	const root = fixture();
	const pages = JSON.parse(readFileSync(join(root, "releases.json"), "utf8"));
	const release = pages[1][0];
	let id = 10;
	const addPlatform = (platform: "linux" | "win32") => {
		for (const arch of ["x64", "arm64"]) {
			const artifact = `Clawdi-${platform}-${arch}${platform === "win32" ? "-unsigned.exe" : ".AppImage"}`;
			release.assets.push({ name: `beta-${platform}-${arch}.yml`, id }, { name: artifact });
			if (platform === "win32") release.assets.push({ name: `${artifact}.blockmap` });
			writeFileSync(
				join(root, `asset-${id}.json`),
				JSON.stringify({
					version: "1.1.0-beta.10",
					path: artifact,
					files: [{ url: artifact, sha512: "hash", size: 1 }],
				}),
			);
			id++;
		}
		writeFileSync(join(root, "releases.json"), JSON.stringify(pages));
	};
	writeFileSync(
		join(root, "bin/gh"),
		`#!/bin/sh
case "$2" in
  */assets/2) cat "$FIXTURE_ROOT/stable.json" ;;
  */assets/1) cat "$FIXTURE_ROOT/metadata.json" ;;
  *releases/assets/*) cat "$FIXTURE_ROOT/asset-\${2##*/}.json" ;;
  *) cat "$FIXTURE_ROOT/releases.json" ;;
esac
`,
		{ mode: 0o700 },
	);
	addPlatform("linux");
	expect((await prepare(root)).code).toBe(0);
	expect(existsSync(join(root, "site/desktop/win32-x64/beta.yml"))).toBe(false);

	addPlatform("win32");
	expect((await prepare(root)).code).toBe(0);
	for (const platform of ["win32", "linux"]) {
		for (const arch of ["x64", "arm64"]) {
			const suffix = platform === "win32" ? "" : `-linux${arch === "arm64" ? "-arm64" : ""}`;
			const metadata = parse(
				readFileSync(join(root, `site/desktop/${platform}-${arch}/beta${suffix}.yml`), "utf8"),
			);
			expect(metadata.files[0].url).toContain(
				`Clawdi-${platform}-${arch}${platform === "win32" ? "-unsigned.exe" : ".AppImage"}`,
			);
		}
	}
	const completeAssets = release.assets;
	release.assets = completeAssets.filter(
		(asset: { name: string }) => asset.name !== "Clawdi-win32-x64-unsigned.exe.blockmap",
	);
	writeFileSync(join(root, "releases.json"), JSON.stringify(pages));
	const missingBlockmap = await prepare(root);
	expect(missingBlockmap.code).not.toBe(0);
	expect(missingBlockmap.error).toContain("Missing NSIS blockmap");
	release.assets = completeAssets.filter(
		(asset: { name: string }) => asset.name !== "beta-win32-arm64.yml",
	);
	writeFileSync(join(root, "releases.json"), JSON.stringify(pages));
	const result = await prepare(root);
	expect(result.code).not.toBe(0);
	expect(result.error).toContain("Incomplete Desktop release");
});
