export const deploymentsEn = {
	title: "Cloud deployments",
	description: "Deployment status from the v2 control plane.",
	detail: "Deployment progress",
	unavailable: "Cloud deployment access is not configured.",
	empty: "No cloud deployments yet.",
	refresh: "Refresh status",
	timeout: "Automatic status checks have paused. Refresh to check again.",
	paused: "Status checks pause while the app is in the background or offline.",
	unknown: "Waiting for server status",
	agent: "View Cloud Agent",
	agentUnavailable: "Cloud Agent identity is not available yet.",
	noSessions: "A deployment can be ready before any Sessions exist. Sessions are read only.",
	operation: "Operation",
	complete: "Complete",
	progress: "In progress",
	failed: "Deployment failed",
	creating: "Creating deployment",
	starting: "Starting runtime",
	running: "Runtime is running",
	stopping: "Stopping runtime",
	stopped: "Runtime is stopped",
	restarting: "Restarting runtime",
	updating: "Updating runtime",
	deleting: "Deleting deployment",
	deleted: "Deployment deleted",
} as const;
