"""add skill source_repo

Revision ID: 9f74c827cec3
Revises: 1b50ac3f7b87
Create Date: 2026-04-16 15:55:42.338900

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f74c827cec3"
down_revision: str | Sequence[str] | None = "1b50ac3f7b87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("skills", sa.Column("source_repo", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skills", "source_repo")
    # ### end Alembic commands ###
