/**
 * Builds the Uniwind theme from the Web design tokens so mobile and Web share
 * one source of truth: packages/shared/src/style/theme.css.
 *
 * Run `bun run theme` after changing the shared tokens; `theme.test.ts` fails
 * when the committed output is stale.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { possibleNativeClasses } from "@/lib/web-classes";

const sourcePath = fileURLToPath(
	new URL("../../../packages/shared/src/style/theme.css", import.meta.url),
);
export const outputPath = fileURLToPath(new URL("../theme.generated.css", import.meta.url));
/** Web class strings live in shared UI recipes and in view tables (tones, tints, identities). */
const webClassSourceDirs = ["ui", "view"].map((dir) =>
	fileURLToPath(new URL(`../../../packages/shared/src/${dir}`, import.meta.url)),
);
export const webClassesOutputPath = fileURLToPath(
	new URL("../web-classes.generated.css", import.meta.url),
);

const REM_PX = 16;

function block(css: string, selector: string): string {
	const start = css.indexOf(`${selector} {`);
	if (start < 0) throw new Error(`Missing ${selector} block in shared theme`);
	const end = css.indexOf("\n}", start);
	return css.slice(start + selector.length + 2, end);
}

function declarations(body: string): Map<string, string> {
	const result = new Map<string, string>();
	const withoutComments = body.replace(/\/\*[\s\S]*?\*\//g, "");
	for (const match of withoutComments.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) {
		const [, name, value] = match;
		if (name && value) result.set(name, value.trim());
	}
	return result;
}

/** Tokens exposed as Tailwind colors via `--color-<token>: var(--<token>)`. */
function colorTokens(themeInline: Map<string, string>): string[] {
	const tokens: string[] = [];
	for (const [name, value] of themeInline) {
		const match = /^--color-([\w-]+)$/.exec(name);
		if (match?.[1] && value === `var(--${match[1]})`) tokens.push(match[1]);
	}
	return tokens;
}

function themeVariant(values: Map<string, string>, tokens: readonly string[], indent: string) {
	return tokens
		.map((token) => {
			const value = values.get(`--${token}`);
			if (!value) throw new Error(`Shared theme is missing --${token}`);
			return `${indent}--color-${token}: ${value};`;
		})
		.join("\n");
}

function remToPx(value: string): number {
	const match = /^([\d.]+)rem$/.exec(value);
	if (!match?.[1]) throw new Error(`Expected rem value, received ${value}`);
	return Number(match[1]) * REM_PX;
}

export function buildMobileTheme(css: string): string {
	const light = declarations(block(css, ":root"));
	const dark = declarations(block(css, ".dark"));
	const themeInline = declarations(block(css, "@theme inline"));
	const tokens = colorTokens(themeInline);
	const radius = remToPx(light.get("--radius") ?? "");
	const text = ["2xs", "3xs"]
		.flatMap((size) => [
			`\t--text-${size}: ${themeInline.get(`--text-${size}`)};`,
			`\t--text-${size}--line-height: ${themeInline.get(`--text-${size}--line-height`)};`,
		])
		.join("\n");
	return `/* Generated by apps/mobile/scripts/theme.ts from packages/shared/src/style/theme.css. Do not edit. */

@layer theme {
	:root {
		@variant light {
${themeVariant(light, tokens, "\t\t\t")}
		}
		@variant dark {
${themeVariant(dark, tokens, "\t\t\t")}
		}
	}
}

@theme {
	--radius-sm: ${radius - 4}px;
	--radius-md: ${radius - 2}px;
	--radius-lg: ${radius}px;
	--radius-xl: ${radius + 4}px;
${text}
}
`;
}

/**
 * Uniwind only compiles classes it finds literally in source. Web class strings
 * resolved at runtime (`hover:x` -> `active:x`, ...) are safelisted here.
 */
function skipPast(source: string, marker: string, from: number): number {
	const end = source.indexOf(marker, from);
	return end < 0 ? source.length : end + marker.length;
}

/** String literal contents, including static template chunks; comments are skipped. */
export function stringLiterals(source: string): string[] {
	const literals: string[] = [];
	let index = 0;
	const quoted = (quote: string) => {
		let value = "";
		for (index++; index < source.length && source[index] !== quote; index++) {
			if (source[index] === "\\") index++;
			value += source[index] ?? "";
		}
		index++;
		literals.push(value);
	};
	const template = () => {
		let chunk = "";
		for (index++; index < source.length && source[index] !== "`"; index++) {
			if (source[index] === "\\") {
				chunk += source[++index] ?? "";
			} else if (source.startsWith("${", index)) {
				literals.push(chunk);
				chunk = "";
				index += 2;
				code("}");
			} else chunk += source[index];
		}
		index++;
		literals.push(chunk);
	};
	const code = (until?: string) => {
		let depth = 0;
		while (index < source.length) {
			const char = source[index] ?? "";
			if (until && char === until && depth === 0) return;
			if (source.startsWith("//", index)) index = skipPast(source, "\n", index);
			else if (source.startsWith("/*", index)) index = skipPast(source, "*/", index);
			else if (char === '"' || char === "'") quoted(char);
			else if (char === "`") template();
			else {
				if (char === "{") depth++;
				if (char === "}") depth--;
				index++;
			}
		}
	};
	code();
	return literals;
}

/**
 * `@source inline()` parses quotes, braces and parentheses: one copy token such as
 * `project's`, `{count}` or `(BYOK)` silently drops every class after it.
 */
function isInlineCandidate(name: string): boolean {
	if (!/^[\w!@*-]/.test(name) || /["'`\\{}]/.test(name)) return false;
	let parens = 0;
	let brackets = 0;
	for (const char of name) {
		if (char === "(") parens++;
		else if (char === ")") parens--;
		else if (char === "[") brackets++;
		else if (char === "]") brackets--;
		if (parens < 0 || brackets < 0) return false;
	}
	return parens === 0 && brackets === 0;
}

export function buildWebClassSafelist(sources: readonly string[]): string {
	const classes = new Set<string>();
	for (const literal of sources.flatMap(stringLiterals)) {
		for (const name of possibleNativeClasses(literal)) {
			if (isInlineCandidate(name)) classes.add(name);
		}
	}
	const sorted = [...classes].sort();
	return `/* Generated by apps/mobile/scripts/theme.ts from packages/shared/src/{ui,view}. Do not edit. */\n@source inline("${sorted.join(" ")}");\n`;
}

export function readWebClassSources(): string[] {
	return webClassSourceDirs.flatMap((dir) =>
		readdirSync(dir, { recursive: true })
			.map(String)
			.filter((file) => file.endsWith(".ts") && !file.endsWith(".test.ts"))
			.sort()
			.map((file) => readFileSync(join(dir, file), "utf8")),
	);
}

if (import.meta.main) {
	writeFileSync(outputPath, buildMobileTheme(readFileSync(sourcePath, "utf8")));
	writeFileSync(webClassesOutputPath, buildWebClassSafelist(readWebClassSources()));
}

export function readSharedTheme() {
	return readFileSync(sourcePath, "utf8");
}
