/**
 * Builds the Uniwind theme from the Web design tokens so mobile and Web share
 * one source of truth: packages/shared/src/style/theme.css.
 *
 * Run `bun run theme` after changing the shared tokens; `theme.test.ts` fails
 * when the committed output is stale.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { possibleNativeClasses } from "@/lib/web-classes";

const sourcePath = fileURLToPath(
	new URL("../../../packages/shared/src/style/theme.css", import.meta.url),
);
export const outputPath = fileURLToPath(new URL("../theme.generated.css", import.meta.url));
const webClassSourceDir = fileURLToPath(
	new URL("../../../packages/shared/src/ui", import.meta.url),
);
export const webClassesOutputPath = fileURLToPath(
	new URL("../web-classes.generated.css", import.meta.url),
);

const REM_PX = 16;

function block(css: string, selector: string): string {
	const start = css.indexOf(`${selector} {`);
	if (start < 0) throw new Error(`Missing ${selector} block in shared theme`);
	const end = css.indexOf("\n}", start);
	return css.slice(start + selector.length + 2, end);
}

function declarations(body: string): Map<string, string> {
	const result = new Map<string, string>();
	const withoutComments = body.replace(/\/\*[\s\S]*?\*\//g, "");
	for (const match of withoutComments.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) {
		const [, name, value] = match;
		if (name && value) result.set(name, value.trim());
	}
	return result;
}

/** Tokens exposed as Tailwind colors via `--color-<token>: var(--<token>)`. */
function colorTokens(themeInline: Map<string, string>): string[] {
	const tokens: string[] = [];
	for (const [name, value] of themeInline) {
		const match = /^--color-([\w-]+)$/.exec(name);
		if (match?.[1] && value === `var(--${match[1]})`) tokens.push(match[1]);
	}
	return tokens;
}

function themeVariant(values: Map<string, string>, tokens: readonly string[], indent: string) {
	return tokens
		.map((token) => {
			const value = values.get(`--${token}`);
			if (!value) throw new Error(`Shared theme is missing --${token}`);
			return `${indent}--color-${token}: ${value};`;
		})
		.join("\n");
}

function remToPx(value: string): number {
	const match = /^([\d.]+)rem$/.exec(value);
	if (!match?.[1]) throw new Error(`Expected rem value, received ${value}`);
	return Number(match[1]) * REM_PX;
}

export function buildMobileTheme(css: string): string {
	const light = declarations(block(css, ":root"));
	const dark = declarations(block(css, ".dark"));
	const themeInline = declarations(block(css, "@theme inline"));
	const tokens = colorTokens(themeInline);
	const radius = remToPx(light.get("--radius") ?? "");
	const text = ["2xs", "3xs"]
		.flatMap((size) => [
			`\t--text-${size}: ${themeInline.get(`--text-${size}`)};`,
			`\t--text-${size}--line-height: ${themeInline.get(`--text-${size}--line-height`)};`,
		])
		.join("\n");
	return `/* Generated by apps/mobile/scripts/theme.ts from packages/shared/src/style/theme.css. Do not edit. */

@layer theme {
	:root {
		@variant light {
${themeVariant(light, tokens, "\t\t\t")}
		}
		@variant dark {
${themeVariant(dark, tokens, "\t\t\t")}
		}
	}
}

@theme {
	--radius-sm: ${radius - 4}px;
	--radius-md: ${radius - 2}px;
	--radius-lg: ${radius}px;
	--radius-xl: ${radius + 4}px;
${text}
}
`;
}

/**
 * Uniwind only compiles classes it finds literally in source. Web class strings
 * resolved at runtime (`hover:x` -> `active:x`, ...) are safelisted here.
 */
export function buildWebClassSafelist(sources: readonly string[]): string {
	const classes = new Set<string>();
	for (const source of sources) {
		for (const match of source.matchAll(/"([^"\n]*)"/g)) {
			for (const name of possibleNativeClasses(match[1] ?? "")) classes.add(name);
		}
	}
	const sorted = [...classes].sort();
	return `/* Generated by apps/mobile/scripts/theme.ts from packages/shared/src/ui. Do not edit. */\n@source inline("${sorted.join(" ")}");\n`;
}

export function readWebClassSources(): string[] {
	return readdirSync(webClassSourceDir, { recursive: true })
		.map(String)
		.filter((file) => file.endsWith(".ts") && !file.endsWith(".test.ts"))
		.sort()
		.map((file) => readFileSync(join(webClassSourceDir, file), "utf8"));
}

if (import.meta.main) {
	writeFileSync(outputPath, buildMobileTheme(readFileSync(sourcePath, "utf8")));
	writeFileSync(webClassesOutputPath, buildWebClassSafelist(readWebClassSources()));
}

export function readSharedTheme() {
	return readFileSync(sourcePath, "utf8");
}
